// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/address"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/business"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/predicate"
)

// AddressUpdate is the builder for updating Address entities.
type AddressUpdate struct {
	config
	hooks    []Hook
	mutation *AddressMutation
}

// Where appends a list predicates to the AddressUpdate builder.
func (au *AddressUpdate) Where(ps ...predicate.Address) *AddressUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetPrefecture sets the "Prefecture" field.
func (au *AddressUpdate) SetPrefecture(s string) *AddressUpdate {
	au.mutation.SetPrefecture(s)
	return au
}

// SetNillablePrefecture sets the "Prefecture" field if the given value is not nil.
func (au *AddressUpdate) SetNillablePrefecture(s *string) *AddressUpdate {
	if s != nil {
		au.SetPrefecture(*s)
	}
	return au
}

// ClearPrefecture clears the value of the "Prefecture" field.
func (au *AddressUpdate) ClearPrefecture() *AddressUpdate {
	au.mutation.ClearPrefecture()
	return au
}

// SetCity sets the "City" field.
func (au *AddressUpdate) SetCity(s string) *AddressUpdate {
	au.mutation.SetCity(s)
	return au
}

// SetNillableCity sets the "City" field if the given value is not nil.
func (au *AddressUpdate) SetNillableCity(s *string) *AddressUpdate {
	if s != nil {
		au.SetCity(*s)
	}
	return au
}

// ClearCity clears the value of the "City" field.
func (au *AddressUpdate) ClearCity() *AddressUpdate {
	au.mutation.ClearCity()
	return au
}

// SetPostcode sets the "Postcode" field.
func (au *AddressUpdate) SetPostcode(s string) *AddressUpdate {
	au.mutation.SetPostcode(s)
	return au
}

// SetNillablePostcode sets the "Postcode" field if the given value is not nil.
func (au *AddressUpdate) SetNillablePostcode(s *string) *AddressUpdate {
	if s != nil {
		au.SetPostcode(*s)
	}
	return au
}

// ClearPostcode clears the value of the "Postcode" field.
func (au *AddressUpdate) ClearPostcode() *AddressUpdate {
	au.mutation.ClearPostcode()
	return au
}

// SetBusinessID sets the "business" edge to the Business entity by ID.
func (au *AddressUpdate) SetBusinessID(id int) *AddressUpdate {
	au.mutation.SetBusinessID(id)
	return au
}

// SetBusiness sets the "business" edge to the Business entity.
func (au *AddressUpdate) SetBusiness(b *Business) *AddressUpdate {
	return au.SetBusinessID(b.ID)
}

// Mutation returns the AddressMutation object of the builder.
func (au *AddressUpdate) Mutation() *AddressMutation {
	return au.mutation
}

// ClearBusiness clears the "business" edge to the Business entity.
func (au *AddressUpdate) ClearBusiness() *AddressUpdate {
	au.mutation.ClearBusiness()
	return au
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AddressUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AddressUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AddressUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AddressUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AddressUpdate) check() error {
	if au.mutation.BusinessCleared() && len(au.mutation.BusinessIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Address.business"`)
	}
	return nil
}

func (au *AddressUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(address.Table, address.Columns, sqlgraph.NewFieldSpec(address.FieldID, field.TypeInt))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Prefecture(); ok {
		_spec.SetField(address.FieldPrefecture, field.TypeString, value)
	}
	if au.mutation.PrefectureCleared() {
		_spec.ClearField(address.FieldPrefecture, field.TypeString)
	}
	if value, ok := au.mutation.City(); ok {
		_spec.SetField(address.FieldCity, field.TypeString, value)
	}
	if au.mutation.CityCleared() {
		_spec.ClearField(address.FieldCity, field.TypeString)
	}
	if value, ok := au.mutation.Postcode(); ok {
		_spec.SetField(address.FieldPostcode, field.TypeString, value)
	}
	if au.mutation.PostcodeCleared() {
		_spec.ClearField(address.FieldPostcode, field.TypeString)
	}
	if au.mutation.BusinessCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.BusinessTable,
			Columns: []string{address.BusinessColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(business.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.BusinessIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.BusinessTable,
			Columns: []string{address.BusinessColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(business.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{address.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AddressUpdateOne is the builder for updating a single Address entity.
type AddressUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AddressMutation
}

// SetPrefecture sets the "Prefecture" field.
func (auo *AddressUpdateOne) SetPrefecture(s string) *AddressUpdateOne {
	auo.mutation.SetPrefecture(s)
	return auo
}

// SetNillablePrefecture sets the "Prefecture" field if the given value is not nil.
func (auo *AddressUpdateOne) SetNillablePrefecture(s *string) *AddressUpdateOne {
	if s != nil {
		auo.SetPrefecture(*s)
	}
	return auo
}

// ClearPrefecture clears the value of the "Prefecture" field.
func (auo *AddressUpdateOne) ClearPrefecture() *AddressUpdateOne {
	auo.mutation.ClearPrefecture()
	return auo
}

// SetCity sets the "City" field.
func (auo *AddressUpdateOne) SetCity(s string) *AddressUpdateOne {
	auo.mutation.SetCity(s)
	return auo
}

// SetNillableCity sets the "City" field if the given value is not nil.
func (auo *AddressUpdateOne) SetNillableCity(s *string) *AddressUpdateOne {
	if s != nil {
		auo.SetCity(*s)
	}
	return auo
}

// ClearCity clears the value of the "City" field.
func (auo *AddressUpdateOne) ClearCity() *AddressUpdateOne {
	auo.mutation.ClearCity()
	return auo
}

// SetPostcode sets the "Postcode" field.
func (auo *AddressUpdateOne) SetPostcode(s string) *AddressUpdateOne {
	auo.mutation.SetPostcode(s)
	return auo
}

// SetNillablePostcode sets the "Postcode" field if the given value is not nil.
func (auo *AddressUpdateOne) SetNillablePostcode(s *string) *AddressUpdateOne {
	if s != nil {
		auo.SetPostcode(*s)
	}
	return auo
}

// ClearPostcode clears the value of the "Postcode" field.
func (auo *AddressUpdateOne) ClearPostcode() *AddressUpdateOne {
	auo.mutation.ClearPostcode()
	return auo
}

// SetBusinessID sets the "business" edge to the Business entity by ID.
func (auo *AddressUpdateOne) SetBusinessID(id int) *AddressUpdateOne {
	auo.mutation.SetBusinessID(id)
	return auo
}

// SetBusiness sets the "business" edge to the Business entity.
func (auo *AddressUpdateOne) SetBusiness(b *Business) *AddressUpdateOne {
	return auo.SetBusinessID(b.ID)
}

// Mutation returns the AddressMutation object of the builder.
func (auo *AddressUpdateOne) Mutation() *AddressMutation {
	return auo.mutation
}

// ClearBusiness clears the "business" edge to the Business entity.
func (auo *AddressUpdateOne) ClearBusiness() *AddressUpdateOne {
	auo.mutation.ClearBusiness()
	return auo
}

// Where appends a list predicates to the AddressUpdate builder.
func (auo *AddressUpdateOne) Where(ps ...predicate.Address) *AddressUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AddressUpdateOne) Select(field string, fields ...string) *AddressUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Address entity.
func (auo *AddressUpdateOne) Save(ctx context.Context) (*Address, error) {
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AddressUpdateOne) SaveX(ctx context.Context) *Address {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AddressUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AddressUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AddressUpdateOne) check() error {
	if auo.mutation.BusinessCleared() && len(auo.mutation.BusinessIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Address.business"`)
	}
	return nil
}

func (auo *AddressUpdateOne) sqlSave(ctx context.Context) (_node *Address, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(address.Table, address.Columns, sqlgraph.NewFieldSpec(address.FieldID, field.TypeInt))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Address.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, address.FieldID)
		for _, f := range fields {
			if !address.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != address.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Prefecture(); ok {
		_spec.SetField(address.FieldPrefecture, field.TypeString, value)
	}
	if auo.mutation.PrefectureCleared() {
		_spec.ClearField(address.FieldPrefecture, field.TypeString)
	}
	if value, ok := auo.mutation.City(); ok {
		_spec.SetField(address.FieldCity, field.TypeString, value)
	}
	if auo.mutation.CityCleared() {
		_spec.ClearField(address.FieldCity, field.TypeString)
	}
	if value, ok := auo.mutation.Postcode(); ok {
		_spec.SetField(address.FieldPostcode, field.TypeString, value)
	}
	if auo.mutation.PostcodeCleared() {
		_spec.ClearField(address.FieldPostcode, field.TypeString)
	}
	if auo.mutation.BusinessCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.BusinessTable,
			Columns: []string{address.BusinessColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(business.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.BusinessIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.BusinessTable,
			Columns: []string{address.BusinessColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(business.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Address{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{address.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
