// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/address"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/business"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/predicate"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/provider"
)

// BusinessUpdate is the builder for updating Business entities.
type BusinessUpdate struct {
	config
	hooks    []Hook
	mutation *BusinessMutation
}

// Where appends a list predicates to the BusinessUpdate builder.
func (bu *BusinessUpdate) Where(ps ...predicate.Business) *BusinessUpdate {
	bu.mutation.Where(ps...)
	return bu
}

// SetName sets the "Name" field.
func (bu *BusinessUpdate) SetName(s string) *BusinessUpdate {
	bu.mutation.SetName(s)
	return bu
}

// SetNillableName sets the "Name" field if the given value is not nil.
func (bu *BusinessUpdate) SetNillableName(s *string) *BusinessUpdate {
	if s != nil {
		bu.SetName(*s)
	}
	return bu
}

// ClearName clears the value of the "Name" field.
func (bu *BusinessUpdate) ClearName() *BusinessUpdate {
	bu.mutation.ClearName()
	return bu
}

// SetWebsiteLink sets the "WebsiteLink" field.
func (bu *BusinessUpdate) SetWebsiteLink(s string) *BusinessUpdate {
	bu.mutation.SetWebsiteLink(s)
	return bu
}

// SetNillableWebsiteLink sets the "WebsiteLink" field if the given value is not nil.
func (bu *BusinessUpdate) SetNillableWebsiteLink(s *string) *BusinessUpdate {
	if s != nil {
		bu.SetWebsiteLink(*s)
	}
	return bu
}

// ClearWebsiteLink clears the value of the "WebsiteLink" field.
func (bu *BusinessUpdate) ClearWebsiteLink() *BusinessUpdate {
	bu.mutation.ClearWebsiteLink()
	return bu
}

// SetOverview sets the "Overview" field.
func (bu *BusinessUpdate) SetOverview(s string) *BusinessUpdate {
	bu.mutation.SetOverview(s)
	return bu
}

// SetNillableOverview sets the "Overview" field if the given value is not nil.
func (bu *BusinessUpdate) SetNillableOverview(s *string) *BusinessUpdate {
	if s != nil {
		bu.SetOverview(*s)
	}
	return bu
}

// ClearOverview clears the value of the "Overview" field.
func (bu *BusinessUpdate) ClearOverview() *BusinessUpdate {
	bu.mutation.ClearOverview()
	return bu
}

// SetProviderID sets the "provider" edge to the Provider entity by ID.
func (bu *BusinessUpdate) SetProviderID(id int) *BusinessUpdate {
	bu.mutation.SetProviderID(id)
	return bu
}

// SetProvider sets the "provider" edge to the Provider entity.
func (bu *BusinessUpdate) SetProvider(p *Provider) *BusinessUpdate {
	return bu.SetProviderID(p.ID)
}

// AddAddresIDs adds the "address" edge to the Address entity by IDs.
func (bu *BusinessUpdate) AddAddresIDs(ids ...int) *BusinessUpdate {
	bu.mutation.AddAddresIDs(ids...)
	return bu
}

// AddAddress adds the "address" edges to the Address entity.
func (bu *BusinessUpdate) AddAddress(a ...*Address) *BusinessUpdate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return bu.AddAddresIDs(ids...)
}

// Mutation returns the BusinessMutation object of the builder.
func (bu *BusinessUpdate) Mutation() *BusinessMutation {
	return bu.mutation
}

// ClearProvider clears the "provider" edge to the Provider entity.
func (bu *BusinessUpdate) ClearProvider() *BusinessUpdate {
	bu.mutation.ClearProvider()
	return bu
}

// ClearAddress clears all "address" edges to the Address entity.
func (bu *BusinessUpdate) ClearAddress() *BusinessUpdate {
	bu.mutation.ClearAddress()
	return bu
}

// RemoveAddresIDs removes the "address" edge to Address entities by IDs.
func (bu *BusinessUpdate) RemoveAddresIDs(ids ...int) *BusinessUpdate {
	bu.mutation.RemoveAddresIDs(ids...)
	return bu
}

// RemoveAddress removes "address" edges to Address entities.
func (bu *BusinessUpdate) RemoveAddress(a ...*Address) *BusinessUpdate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return bu.RemoveAddresIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bu *BusinessUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, bu.sqlSave, bu.mutation, bu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bu *BusinessUpdate) SaveX(ctx context.Context) int {
	affected, err := bu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bu *BusinessUpdate) Exec(ctx context.Context) error {
	_, err := bu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bu *BusinessUpdate) ExecX(ctx context.Context) {
	if err := bu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bu *BusinessUpdate) check() error {
	if bu.mutation.ProviderCleared() && len(bu.mutation.ProviderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Business.provider"`)
	}
	return nil
}

func (bu *BusinessUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := bu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(business.Table, business.Columns, sqlgraph.NewFieldSpec(business.FieldID, field.TypeInt))
	if ps := bu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bu.mutation.Name(); ok {
		_spec.SetField(business.FieldName, field.TypeString, value)
	}
	if bu.mutation.NameCleared() {
		_spec.ClearField(business.FieldName, field.TypeString)
	}
	if value, ok := bu.mutation.WebsiteLink(); ok {
		_spec.SetField(business.FieldWebsiteLink, field.TypeString, value)
	}
	if bu.mutation.WebsiteLinkCleared() {
		_spec.ClearField(business.FieldWebsiteLink, field.TypeString)
	}
	if value, ok := bu.mutation.Overview(); ok {
		_spec.SetField(business.FieldOverview, field.TypeString, value)
	}
	if bu.mutation.OverviewCleared() {
		_spec.ClearField(business.FieldOverview, field.TypeString)
	}
	if bu.mutation.ProviderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   business.ProviderTable,
			Columns: []string{business.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   business.ProviderTable,
			Columns: []string{business.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if bu.mutation.AddressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   business.AddressTable,
			Columns: []string{business.AddressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(address.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.RemovedAddressIDs(); len(nodes) > 0 && !bu.mutation.AddressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   business.AddressTable,
			Columns: []string{business.AddressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(address.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.AddressIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   business.AddressTable,
			Columns: []string{business.AddressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(address.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{business.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	bu.mutation.done = true
	return n, nil
}

// BusinessUpdateOne is the builder for updating a single Business entity.
type BusinessUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BusinessMutation
}

// SetName sets the "Name" field.
func (buo *BusinessUpdateOne) SetName(s string) *BusinessUpdateOne {
	buo.mutation.SetName(s)
	return buo
}

// SetNillableName sets the "Name" field if the given value is not nil.
func (buo *BusinessUpdateOne) SetNillableName(s *string) *BusinessUpdateOne {
	if s != nil {
		buo.SetName(*s)
	}
	return buo
}

// ClearName clears the value of the "Name" field.
func (buo *BusinessUpdateOne) ClearName() *BusinessUpdateOne {
	buo.mutation.ClearName()
	return buo
}

// SetWebsiteLink sets the "WebsiteLink" field.
func (buo *BusinessUpdateOne) SetWebsiteLink(s string) *BusinessUpdateOne {
	buo.mutation.SetWebsiteLink(s)
	return buo
}

// SetNillableWebsiteLink sets the "WebsiteLink" field if the given value is not nil.
func (buo *BusinessUpdateOne) SetNillableWebsiteLink(s *string) *BusinessUpdateOne {
	if s != nil {
		buo.SetWebsiteLink(*s)
	}
	return buo
}

// ClearWebsiteLink clears the value of the "WebsiteLink" field.
func (buo *BusinessUpdateOne) ClearWebsiteLink() *BusinessUpdateOne {
	buo.mutation.ClearWebsiteLink()
	return buo
}

// SetOverview sets the "Overview" field.
func (buo *BusinessUpdateOne) SetOverview(s string) *BusinessUpdateOne {
	buo.mutation.SetOverview(s)
	return buo
}

// SetNillableOverview sets the "Overview" field if the given value is not nil.
func (buo *BusinessUpdateOne) SetNillableOverview(s *string) *BusinessUpdateOne {
	if s != nil {
		buo.SetOverview(*s)
	}
	return buo
}

// ClearOverview clears the value of the "Overview" field.
func (buo *BusinessUpdateOne) ClearOverview() *BusinessUpdateOne {
	buo.mutation.ClearOverview()
	return buo
}

// SetProviderID sets the "provider" edge to the Provider entity by ID.
func (buo *BusinessUpdateOne) SetProviderID(id int) *BusinessUpdateOne {
	buo.mutation.SetProviderID(id)
	return buo
}

// SetProvider sets the "provider" edge to the Provider entity.
func (buo *BusinessUpdateOne) SetProvider(p *Provider) *BusinessUpdateOne {
	return buo.SetProviderID(p.ID)
}

// AddAddresIDs adds the "address" edge to the Address entity by IDs.
func (buo *BusinessUpdateOne) AddAddresIDs(ids ...int) *BusinessUpdateOne {
	buo.mutation.AddAddresIDs(ids...)
	return buo
}

// AddAddress adds the "address" edges to the Address entity.
func (buo *BusinessUpdateOne) AddAddress(a ...*Address) *BusinessUpdateOne {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return buo.AddAddresIDs(ids...)
}

// Mutation returns the BusinessMutation object of the builder.
func (buo *BusinessUpdateOne) Mutation() *BusinessMutation {
	return buo.mutation
}

// ClearProvider clears the "provider" edge to the Provider entity.
func (buo *BusinessUpdateOne) ClearProvider() *BusinessUpdateOne {
	buo.mutation.ClearProvider()
	return buo
}

// ClearAddress clears all "address" edges to the Address entity.
func (buo *BusinessUpdateOne) ClearAddress() *BusinessUpdateOne {
	buo.mutation.ClearAddress()
	return buo
}

// RemoveAddresIDs removes the "address" edge to Address entities by IDs.
func (buo *BusinessUpdateOne) RemoveAddresIDs(ids ...int) *BusinessUpdateOne {
	buo.mutation.RemoveAddresIDs(ids...)
	return buo
}

// RemoveAddress removes "address" edges to Address entities.
func (buo *BusinessUpdateOne) RemoveAddress(a ...*Address) *BusinessUpdateOne {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return buo.RemoveAddresIDs(ids...)
}

// Where appends a list predicates to the BusinessUpdate builder.
func (buo *BusinessUpdateOne) Where(ps ...predicate.Business) *BusinessUpdateOne {
	buo.mutation.Where(ps...)
	return buo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (buo *BusinessUpdateOne) Select(field string, fields ...string) *BusinessUpdateOne {
	buo.fields = append([]string{field}, fields...)
	return buo
}

// Save executes the query and returns the updated Business entity.
func (buo *BusinessUpdateOne) Save(ctx context.Context) (*Business, error) {
	return withHooks(ctx, buo.sqlSave, buo.mutation, buo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (buo *BusinessUpdateOne) SaveX(ctx context.Context) *Business {
	node, err := buo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (buo *BusinessUpdateOne) Exec(ctx context.Context) error {
	_, err := buo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (buo *BusinessUpdateOne) ExecX(ctx context.Context) {
	if err := buo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (buo *BusinessUpdateOne) check() error {
	if buo.mutation.ProviderCleared() && len(buo.mutation.ProviderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Business.provider"`)
	}
	return nil
}

func (buo *BusinessUpdateOne) sqlSave(ctx context.Context) (_node *Business, err error) {
	if err := buo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(business.Table, business.Columns, sqlgraph.NewFieldSpec(business.FieldID, field.TypeInt))
	id, ok := buo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Business.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := buo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, business.FieldID)
		for _, f := range fields {
			if !business.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != business.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := buo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := buo.mutation.Name(); ok {
		_spec.SetField(business.FieldName, field.TypeString, value)
	}
	if buo.mutation.NameCleared() {
		_spec.ClearField(business.FieldName, field.TypeString)
	}
	if value, ok := buo.mutation.WebsiteLink(); ok {
		_spec.SetField(business.FieldWebsiteLink, field.TypeString, value)
	}
	if buo.mutation.WebsiteLinkCleared() {
		_spec.ClearField(business.FieldWebsiteLink, field.TypeString)
	}
	if value, ok := buo.mutation.Overview(); ok {
		_spec.SetField(business.FieldOverview, field.TypeString, value)
	}
	if buo.mutation.OverviewCleared() {
		_spec.ClearField(business.FieldOverview, field.TypeString)
	}
	if buo.mutation.ProviderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   business.ProviderTable,
			Columns: []string{business.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   business.ProviderTable,
			Columns: []string{business.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if buo.mutation.AddressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   business.AddressTable,
			Columns: []string{business.AddressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(address.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.RemovedAddressIDs(); len(nodes) > 0 && !buo.mutation.AddressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   business.AddressTable,
			Columns: []string{business.AddressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(address.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.AddressIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   business.AddressTable,
			Columns: []string{business.AddressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(address.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Business{config: buo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, buo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{business.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	buo.mutation.done = true
	return _node, nil
}
