// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/caller"
)

// Caller is the model entity for the Caller schema.
type Caller struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// IsFraud holds the value of the "IsFraud" field.
	IsFraud bool `json:"IsFraud,omitempty"`
	// FraudScore holds the value of the "FraudScore" field.
	FraudScore int `json:"FraudScore,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CallerQuery when eager-loading is set.
	Edges        CallerEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CallerEdges holds the relations/edges for other nodes in the graph.
type CallerEdges struct {
	// Number holds the value of the number edge.
	Number []*Number `json:"number,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// NumberOrErr returns the Number value or an error if the edge
// was not loaded in eager-loading.
func (e CallerEdges) NumberOrErr() ([]*Number, error) {
	if e.loadedTypes[0] {
		return e.Number, nil
	}
	return nil, &NotLoadedError{edge: "number"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Caller) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case caller.FieldIsFraud:
			values[i] = new(sql.NullBool)
		case caller.FieldID, caller.FieldFraudScore:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Caller fields.
func (c *Caller) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case caller.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			c.ID = int(value.Int64)
		case caller.FieldIsFraud:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field IsFraud", values[i])
			} else if value.Valid {
				c.IsFraud = value.Bool
			}
		case caller.FieldFraudScore:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field FraudScore", values[i])
			} else if value.Valid {
				c.FraudScore = int(value.Int64)
			}
		default:
			c.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Caller.
// This includes values selected through modifiers, order, etc.
func (c *Caller) Value(name string) (ent.Value, error) {
	return c.selectValues.Get(name)
}

// QueryNumber queries the "number" edge of the Caller entity.
func (c *Caller) QueryNumber() *NumberQuery {
	return NewCallerClient(c.config).QueryNumber(c)
}

// Update returns a builder for updating this Caller.
// Note that you need to call Caller.Unwrap() before calling this method if this Caller
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Caller) Update() *CallerUpdateOne {
	return NewCallerClient(c.config).UpdateOne(c)
}

// Unwrap unwraps the Caller entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (c *Caller) Unwrap() *Caller {
	_tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Caller is not a transactional entity")
	}
	c.config.driver = _tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Caller) String() string {
	var builder strings.Builder
	builder.WriteString("Caller(")
	builder.WriteString(fmt.Sprintf("id=%v, ", c.ID))
	builder.WriteString("IsFraud=")
	builder.WriteString(fmt.Sprintf("%v", c.IsFraud))
	builder.WriteString(", ")
	builder.WriteString("FraudScore=")
	builder.WriteString(fmt.Sprintf("%v", c.FraudScore))
	builder.WriteByte(')')
	return builder.String()
}

// Callers is a parsable slice of Caller.
type Callers []*Caller
