// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/caller"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/number"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/predicate"
)

// CallerUpdate is the builder for updating Caller entities.
type CallerUpdate struct {
	config
	hooks    []Hook
	mutation *CallerMutation
}

// Where appends a list predicates to the CallerUpdate builder.
func (cu *CallerUpdate) Where(ps ...predicate.Caller) *CallerUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetIsFraud sets the "IsFraud" field.
func (cu *CallerUpdate) SetIsFraud(b bool) *CallerUpdate {
	cu.mutation.SetIsFraud(b)
	return cu
}

// SetNillableIsFraud sets the "IsFraud" field if the given value is not nil.
func (cu *CallerUpdate) SetNillableIsFraud(b *bool) *CallerUpdate {
	if b != nil {
		cu.SetIsFraud(*b)
	}
	return cu
}

// SetFraudScore sets the "FraudScore" field.
func (cu *CallerUpdate) SetFraudScore(i int) *CallerUpdate {
	cu.mutation.ResetFraudScore()
	cu.mutation.SetFraudScore(i)
	return cu
}

// SetNillableFraudScore sets the "FraudScore" field if the given value is not nil.
func (cu *CallerUpdate) SetNillableFraudScore(i *int) *CallerUpdate {
	if i != nil {
		cu.SetFraudScore(*i)
	}
	return cu
}

// AddFraudScore adds i to the "FraudScore" field.
func (cu *CallerUpdate) AddFraudScore(i int) *CallerUpdate {
	cu.mutation.AddFraudScore(i)
	return cu
}

// AddNumberIDs adds the "number" edge to the Number entity by IDs.
func (cu *CallerUpdate) AddNumberIDs(ids ...int) *CallerUpdate {
	cu.mutation.AddNumberIDs(ids...)
	return cu
}

// AddNumber adds the "number" edges to the Number entity.
func (cu *CallerUpdate) AddNumber(n ...*Number) *CallerUpdate {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return cu.AddNumberIDs(ids...)
}

// Mutation returns the CallerMutation object of the builder.
func (cu *CallerUpdate) Mutation() *CallerMutation {
	return cu.mutation
}

// ClearNumber clears all "number" edges to the Number entity.
func (cu *CallerUpdate) ClearNumber() *CallerUpdate {
	cu.mutation.ClearNumber()
	return cu
}

// RemoveNumberIDs removes the "number" edge to Number entities by IDs.
func (cu *CallerUpdate) RemoveNumberIDs(ids ...int) *CallerUpdate {
	cu.mutation.RemoveNumberIDs(ids...)
	return cu
}

// RemoveNumber removes "number" edges to Number entities.
func (cu *CallerUpdate) RemoveNumber(n ...*Number) *CallerUpdate {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return cu.RemoveNumberIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CallerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CallerUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CallerUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CallerUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cu *CallerUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(caller.Table, caller.Columns, sqlgraph.NewFieldSpec(caller.FieldID, field.TypeInt))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.IsFraud(); ok {
		_spec.SetField(caller.FieldIsFraud, field.TypeBool, value)
	}
	if value, ok := cu.mutation.FraudScore(); ok {
		_spec.SetField(caller.FieldFraudScore, field.TypeInt, value)
	}
	if value, ok := cu.mutation.AddedFraudScore(); ok {
		_spec.AddField(caller.FieldFraudScore, field.TypeInt, value)
	}
	if cu.mutation.NumberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   caller.NumberTable,
			Columns: []string{caller.NumberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(number.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedNumberIDs(); len(nodes) > 0 && !cu.mutation.NumberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   caller.NumberTable,
			Columns: []string{caller.NumberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(number.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.NumberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   caller.NumberTable,
			Columns: []string{caller.NumberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(number.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{caller.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// CallerUpdateOne is the builder for updating a single Caller entity.
type CallerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CallerMutation
}

// SetIsFraud sets the "IsFraud" field.
func (cuo *CallerUpdateOne) SetIsFraud(b bool) *CallerUpdateOne {
	cuo.mutation.SetIsFraud(b)
	return cuo
}

// SetNillableIsFraud sets the "IsFraud" field if the given value is not nil.
func (cuo *CallerUpdateOne) SetNillableIsFraud(b *bool) *CallerUpdateOne {
	if b != nil {
		cuo.SetIsFraud(*b)
	}
	return cuo
}

// SetFraudScore sets the "FraudScore" field.
func (cuo *CallerUpdateOne) SetFraudScore(i int) *CallerUpdateOne {
	cuo.mutation.ResetFraudScore()
	cuo.mutation.SetFraudScore(i)
	return cuo
}

// SetNillableFraudScore sets the "FraudScore" field if the given value is not nil.
func (cuo *CallerUpdateOne) SetNillableFraudScore(i *int) *CallerUpdateOne {
	if i != nil {
		cuo.SetFraudScore(*i)
	}
	return cuo
}

// AddFraudScore adds i to the "FraudScore" field.
func (cuo *CallerUpdateOne) AddFraudScore(i int) *CallerUpdateOne {
	cuo.mutation.AddFraudScore(i)
	return cuo
}

// AddNumberIDs adds the "number" edge to the Number entity by IDs.
func (cuo *CallerUpdateOne) AddNumberIDs(ids ...int) *CallerUpdateOne {
	cuo.mutation.AddNumberIDs(ids...)
	return cuo
}

// AddNumber adds the "number" edges to the Number entity.
func (cuo *CallerUpdateOne) AddNumber(n ...*Number) *CallerUpdateOne {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return cuo.AddNumberIDs(ids...)
}

// Mutation returns the CallerMutation object of the builder.
func (cuo *CallerUpdateOne) Mutation() *CallerMutation {
	return cuo.mutation
}

// ClearNumber clears all "number" edges to the Number entity.
func (cuo *CallerUpdateOne) ClearNumber() *CallerUpdateOne {
	cuo.mutation.ClearNumber()
	return cuo
}

// RemoveNumberIDs removes the "number" edge to Number entities by IDs.
func (cuo *CallerUpdateOne) RemoveNumberIDs(ids ...int) *CallerUpdateOne {
	cuo.mutation.RemoveNumberIDs(ids...)
	return cuo
}

// RemoveNumber removes "number" edges to Number entities.
func (cuo *CallerUpdateOne) RemoveNumber(n ...*Number) *CallerUpdateOne {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return cuo.RemoveNumberIDs(ids...)
}

// Where appends a list predicates to the CallerUpdate builder.
func (cuo *CallerUpdateOne) Where(ps ...predicate.Caller) *CallerUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CallerUpdateOne) Select(field string, fields ...string) *CallerUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Caller entity.
func (cuo *CallerUpdateOne) Save(ctx context.Context) (*Caller, error) {
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CallerUpdateOne) SaveX(ctx context.Context) *Caller {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CallerUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CallerUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cuo *CallerUpdateOne) sqlSave(ctx context.Context) (_node *Caller, err error) {
	_spec := sqlgraph.NewUpdateSpec(caller.Table, caller.Columns, sqlgraph.NewFieldSpec(caller.FieldID, field.TypeInt))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Caller.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, caller.FieldID)
		for _, f := range fields {
			if !caller.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != caller.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.IsFraud(); ok {
		_spec.SetField(caller.FieldIsFraud, field.TypeBool, value)
	}
	if value, ok := cuo.mutation.FraudScore(); ok {
		_spec.SetField(caller.FieldFraudScore, field.TypeInt, value)
	}
	if value, ok := cuo.mutation.AddedFraudScore(); ok {
		_spec.AddField(caller.FieldFraudScore, field.TypeInt, value)
	}
	if cuo.mutation.NumberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   caller.NumberTable,
			Columns: []string{caller.NumberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(number.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedNumberIDs(); len(nodes) > 0 && !cuo.mutation.NumberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   caller.NumberTable,
			Columns: []string{caller.NumberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(number.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.NumberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   caller.NumberTable,
			Columns: []string{caller.NumberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(number.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Caller{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{caller.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
