// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/carrier"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/number"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/predicate"
)

// CarrierQuery is the builder for querying Carrier entities.
type CarrierQuery struct {
	config
	ctx        *QueryContext
	order      []carrier.OrderOption
	inters     []Interceptor
	predicates []predicate.Carrier
	withNumber *NumberQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CarrierQuery builder.
func (cq *CarrierQuery) Where(ps ...predicate.Carrier) *CarrierQuery {
	cq.predicates = append(cq.predicates, ps...)
	return cq
}

// Limit the number of records to be returned by this query.
func (cq *CarrierQuery) Limit(limit int) *CarrierQuery {
	cq.ctx.Limit = &limit
	return cq
}

// Offset to start from.
func (cq *CarrierQuery) Offset(offset int) *CarrierQuery {
	cq.ctx.Offset = &offset
	return cq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cq *CarrierQuery) Unique(unique bool) *CarrierQuery {
	cq.ctx.Unique = &unique
	return cq
}

// Order specifies how the records should be ordered.
func (cq *CarrierQuery) Order(o ...carrier.OrderOption) *CarrierQuery {
	cq.order = append(cq.order, o...)
	return cq
}

// QueryNumber chains the current query on the "number" edge.
func (cq *CarrierQuery) QueryNumber() *NumberQuery {
	query := (&NumberClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(carrier.Table, carrier.FieldID, selector),
			sqlgraph.To(number.Table, number.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, carrier.NumberTable, carrier.NumberColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Carrier entity from the query.
// Returns a *NotFoundError when no Carrier was found.
func (cq *CarrierQuery) First(ctx context.Context) (*Carrier, error) {
	nodes, err := cq.Limit(1).All(setContextOp(ctx, cq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{carrier.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cq *CarrierQuery) FirstX(ctx context.Context) *Carrier {
	node, err := cq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Carrier ID from the query.
// Returns a *NotFoundError when no Carrier ID was found.
func (cq *CarrierQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cq.Limit(1).IDs(setContextOp(ctx, cq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{carrier.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cq *CarrierQuery) FirstIDX(ctx context.Context) int {
	id, err := cq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Carrier entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Carrier entity is found.
// Returns a *NotFoundError when no Carrier entities are found.
func (cq *CarrierQuery) Only(ctx context.Context) (*Carrier, error) {
	nodes, err := cq.Limit(2).All(setContextOp(ctx, cq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{carrier.Label}
	default:
		return nil, &NotSingularError{carrier.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cq *CarrierQuery) OnlyX(ctx context.Context) *Carrier {
	node, err := cq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Carrier ID in the query.
// Returns a *NotSingularError when more than one Carrier ID is found.
// Returns a *NotFoundError when no entities are found.
func (cq *CarrierQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cq.Limit(2).IDs(setContextOp(ctx, cq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{carrier.Label}
	default:
		err = &NotSingularError{carrier.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cq *CarrierQuery) OnlyIDX(ctx context.Context) int {
	id, err := cq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Carriers.
func (cq *CarrierQuery) All(ctx context.Context) ([]*Carrier, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryAll)
	if err := cq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Carrier, *CarrierQuery]()
	return withInterceptors[[]*Carrier](ctx, cq, qr, cq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cq *CarrierQuery) AllX(ctx context.Context) []*Carrier {
	nodes, err := cq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Carrier IDs.
func (cq *CarrierQuery) IDs(ctx context.Context) (ids []int, err error) {
	if cq.ctx.Unique == nil && cq.path != nil {
		cq.Unique(true)
	}
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryIDs)
	if err = cq.Select(carrier.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cq *CarrierQuery) IDsX(ctx context.Context) []int {
	ids, err := cq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cq *CarrierQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryCount)
	if err := cq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cq, querierCount[*CarrierQuery](), cq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cq *CarrierQuery) CountX(ctx context.Context) int {
	count, err := cq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cq *CarrierQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryExist)
	switch _, err := cq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cq *CarrierQuery) ExistX(ctx context.Context) bool {
	exist, err := cq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CarrierQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cq *CarrierQuery) Clone() *CarrierQuery {
	if cq == nil {
		return nil
	}
	return &CarrierQuery{
		config:     cq.config,
		ctx:        cq.ctx.Clone(),
		order:      append([]carrier.OrderOption{}, cq.order...),
		inters:     append([]Interceptor{}, cq.inters...),
		predicates: append([]predicate.Carrier{}, cq.predicates...),
		withNumber: cq.withNumber.Clone(),
		// clone intermediate query.
		sql:  cq.sql.Clone(),
		path: cq.path,
	}
}

// WithNumber tells the query-builder to eager-load the nodes that are connected to
// the "number" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CarrierQuery) WithNumber(opts ...func(*NumberQuery)) *CarrierQuery {
	query := (&NumberClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withNumber = query
	return cq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"Name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Carrier.Query().
//		GroupBy(carrier.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cq *CarrierQuery) GroupBy(field string, fields ...string) *CarrierGroupBy {
	cq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CarrierGroupBy{build: cq}
	grbuild.flds = &cq.ctx.Fields
	grbuild.label = carrier.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"Name,omitempty"`
//	}
//
//	client.Carrier.Query().
//		Select(carrier.FieldName).
//		Scan(ctx, &v)
func (cq *CarrierQuery) Select(fields ...string) *CarrierSelect {
	cq.ctx.Fields = append(cq.ctx.Fields, fields...)
	sbuild := &CarrierSelect{CarrierQuery: cq}
	sbuild.label = carrier.Label
	sbuild.flds, sbuild.scan = &cq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CarrierSelect configured with the given aggregations.
func (cq *CarrierQuery) Aggregate(fns ...AggregateFunc) *CarrierSelect {
	return cq.Select().Aggregate(fns...)
}

func (cq *CarrierQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cq); err != nil {
				return err
			}
		}
	}
	for _, f := range cq.ctx.Fields {
		if !carrier.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cq.path != nil {
		prev, err := cq.path(ctx)
		if err != nil {
			return err
		}
		cq.sql = prev
	}
	return nil
}

func (cq *CarrierQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Carrier, error) {
	var (
		nodes       = []*Carrier{}
		_spec       = cq.querySpec()
		loadedTypes = [1]bool{
			cq.withNumber != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Carrier).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Carrier{config: cq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cq.withNumber; query != nil {
		if err := cq.loadNumber(ctx, query, nodes,
			func(n *Carrier) { n.Edges.Number = []*Number{} },
			func(n *Carrier, e *Number) { n.Edges.Number = append(n.Edges.Number, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cq *CarrierQuery) loadNumber(ctx context.Context, query *NumberQuery, nodes []*Carrier, init func(*Carrier), assign func(*Carrier, *Number)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Carrier)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Number(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(carrier.NumberColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.carrier_number
		if fk == nil {
			return fmt.Errorf(`foreign-key "carrier_number" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "carrier_number" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (cq *CarrierQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cq.querySpec()
	_spec.Node.Columns = cq.ctx.Fields
	if len(cq.ctx.Fields) > 0 {
		_spec.Unique = cq.ctx.Unique != nil && *cq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cq.driver, _spec)
}

func (cq *CarrierQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(carrier.Table, carrier.Columns, sqlgraph.NewFieldSpec(carrier.FieldID, field.TypeInt))
	_spec.From = cq.sql
	if unique := cq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cq.path != nil {
		_spec.Unique = true
	}
	if fields := cq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, carrier.FieldID)
		for i := range fields {
			if fields[i] != carrier.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cq *CarrierQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cq.driver.Dialect())
	t1 := builder.Table(carrier.Table)
	columns := cq.ctx.Fields
	if len(columns) == 0 {
		columns = carrier.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cq.sql != nil {
		selector = cq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cq.ctx.Unique != nil && *cq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cq.predicates {
		p(selector)
	}
	for _, p := range cq.order {
		p(selector)
	}
	if offset := cq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CarrierGroupBy is the group-by builder for Carrier entities.
type CarrierGroupBy struct {
	selector
	build *CarrierQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cgb *CarrierGroupBy) Aggregate(fns ...AggregateFunc) *CarrierGroupBy {
	cgb.fns = append(cgb.fns, fns...)
	return cgb
}

// Scan applies the selector query and scans the result into the given value.
func (cgb *CarrierGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cgb.build.ctx, ent.OpQueryGroupBy)
	if err := cgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CarrierQuery, *CarrierGroupBy](ctx, cgb.build, cgb, cgb.build.inters, v)
}

func (cgb *CarrierGroupBy) sqlScan(ctx context.Context, root *CarrierQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cgb.fns))
	for _, fn := range cgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cgb.flds)+len(cgb.fns))
		for _, f := range *cgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CarrierSelect is the builder for selecting fields of Carrier entities.
type CarrierSelect struct {
	*CarrierQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cs *CarrierSelect) Aggregate(fns ...AggregateFunc) *CarrierSelect {
	cs.fns = append(cs.fns, fns...)
	return cs
}

// Scan applies the selector query and scans the result into the given value.
func (cs *CarrierSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cs.ctx, ent.OpQuerySelect)
	if err := cs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CarrierQuery, *CarrierSelect](ctx, cs.CarrierQuery, cs, cs.inters, v)
}

func (cs *CarrierSelect) sqlScan(ctx context.Context, root *CarrierQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cs.fns))
	for _, fn := range cs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
