// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/carrier"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/number"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/predicate"
)

// CarrierUpdate is the builder for updating Carrier entities.
type CarrierUpdate struct {
	config
	hooks    []Hook
	mutation *CarrierMutation
}

// Where appends a list predicates to the CarrierUpdate builder.
func (cu *CarrierUpdate) Where(ps ...predicate.Carrier) *CarrierUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetName sets the "Name" field.
func (cu *CarrierUpdate) SetName(s string) *CarrierUpdate {
	cu.mutation.SetName(s)
	return cu
}

// SetNillableName sets the "Name" field if the given value is not nil.
func (cu *CarrierUpdate) SetNillableName(s *string) *CarrierUpdate {
	if s != nil {
		cu.SetName(*s)
	}
	return cu
}

// ClearName clears the value of the "Name" field.
func (cu *CarrierUpdate) ClearName() *CarrierUpdate {
	cu.mutation.ClearName()
	return cu
}

// AddNumberIDs adds the "number" edge to the Number entity by IDs.
func (cu *CarrierUpdate) AddNumberIDs(ids ...int) *CarrierUpdate {
	cu.mutation.AddNumberIDs(ids...)
	return cu
}

// AddNumber adds the "number" edges to the Number entity.
func (cu *CarrierUpdate) AddNumber(n ...*Number) *CarrierUpdate {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return cu.AddNumberIDs(ids...)
}

// Mutation returns the CarrierMutation object of the builder.
func (cu *CarrierUpdate) Mutation() *CarrierMutation {
	return cu.mutation
}

// ClearNumber clears all "number" edges to the Number entity.
func (cu *CarrierUpdate) ClearNumber() *CarrierUpdate {
	cu.mutation.ClearNumber()
	return cu
}

// RemoveNumberIDs removes the "number" edge to Number entities by IDs.
func (cu *CarrierUpdate) RemoveNumberIDs(ids ...int) *CarrierUpdate {
	cu.mutation.RemoveNumberIDs(ids...)
	return cu
}

// RemoveNumber removes "number" edges to Number entities.
func (cu *CarrierUpdate) RemoveNumber(n ...*Number) *CarrierUpdate {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return cu.RemoveNumberIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CarrierUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CarrierUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CarrierUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CarrierUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cu *CarrierUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(carrier.Table, carrier.Columns, sqlgraph.NewFieldSpec(carrier.FieldID, field.TypeInt))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Name(); ok {
		_spec.SetField(carrier.FieldName, field.TypeString, value)
	}
	if cu.mutation.NameCleared() {
		_spec.ClearField(carrier.FieldName, field.TypeString)
	}
	if cu.mutation.NumberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carrier.NumberTable,
			Columns: []string{carrier.NumberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(number.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedNumberIDs(); len(nodes) > 0 && !cu.mutation.NumberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carrier.NumberTable,
			Columns: []string{carrier.NumberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(number.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.NumberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carrier.NumberTable,
			Columns: []string{carrier.NumberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(number.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{carrier.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// CarrierUpdateOne is the builder for updating a single Carrier entity.
type CarrierUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CarrierMutation
}

// SetName sets the "Name" field.
func (cuo *CarrierUpdateOne) SetName(s string) *CarrierUpdateOne {
	cuo.mutation.SetName(s)
	return cuo
}

// SetNillableName sets the "Name" field if the given value is not nil.
func (cuo *CarrierUpdateOne) SetNillableName(s *string) *CarrierUpdateOne {
	if s != nil {
		cuo.SetName(*s)
	}
	return cuo
}

// ClearName clears the value of the "Name" field.
func (cuo *CarrierUpdateOne) ClearName() *CarrierUpdateOne {
	cuo.mutation.ClearName()
	return cuo
}

// AddNumberIDs adds the "number" edge to the Number entity by IDs.
func (cuo *CarrierUpdateOne) AddNumberIDs(ids ...int) *CarrierUpdateOne {
	cuo.mutation.AddNumberIDs(ids...)
	return cuo
}

// AddNumber adds the "number" edges to the Number entity.
func (cuo *CarrierUpdateOne) AddNumber(n ...*Number) *CarrierUpdateOne {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return cuo.AddNumberIDs(ids...)
}

// Mutation returns the CarrierMutation object of the builder.
func (cuo *CarrierUpdateOne) Mutation() *CarrierMutation {
	return cuo.mutation
}

// ClearNumber clears all "number" edges to the Number entity.
func (cuo *CarrierUpdateOne) ClearNumber() *CarrierUpdateOne {
	cuo.mutation.ClearNumber()
	return cuo
}

// RemoveNumberIDs removes the "number" edge to Number entities by IDs.
func (cuo *CarrierUpdateOne) RemoveNumberIDs(ids ...int) *CarrierUpdateOne {
	cuo.mutation.RemoveNumberIDs(ids...)
	return cuo
}

// RemoveNumber removes "number" edges to Number entities.
func (cuo *CarrierUpdateOne) RemoveNumber(n ...*Number) *CarrierUpdateOne {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return cuo.RemoveNumberIDs(ids...)
}

// Where appends a list predicates to the CarrierUpdate builder.
func (cuo *CarrierUpdateOne) Where(ps ...predicate.Carrier) *CarrierUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CarrierUpdateOne) Select(field string, fields ...string) *CarrierUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Carrier entity.
func (cuo *CarrierUpdateOne) Save(ctx context.Context) (*Carrier, error) {
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CarrierUpdateOne) SaveX(ctx context.Context) *Carrier {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CarrierUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CarrierUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cuo *CarrierUpdateOne) sqlSave(ctx context.Context) (_node *Carrier, err error) {
	_spec := sqlgraph.NewUpdateSpec(carrier.Table, carrier.Columns, sqlgraph.NewFieldSpec(carrier.FieldID, field.TypeInt))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Carrier.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, carrier.FieldID)
		for _, f := range fields {
			if !carrier.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != carrier.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Name(); ok {
		_spec.SetField(carrier.FieldName, field.TypeString, value)
	}
	if cuo.mutation.NameCleared() {
		_spec.ClearField(carrier.FieldName, field.TypeString)
	}
	if cuo.mutation.NumberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carrier.NumberTable,
			Columns: []string{carrier.NumberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(number.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedNumberIDs(); len(nodes) > 0 && !cuo.mutation.NumberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carrier.NumberTable,
			Columns: []string{carrier.NumberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(number.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.NumberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carrier.NumberTable,
			Columns: []string{carrier.NumberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(number.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Carrier{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{carrier.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
