// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/carrier"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/number"
)

// CarrierCreate is the builder for creating a Carrier entity.
type CarrierCreate struct {
	config
	mutation *CarrierMutation
	hooks    []Hook
}

// SetName sets the "Name" field.
func (cc *CarrierCreate) SetName(s string) *CarrierCreate {
	cc.mutation.SetName(s)
	return cc
}

// SetNillableName sets the "Name" field if the given value is not nil.
func (cc *CarrierCreate) SetNillableName(s *string) *CarrierCreate {
	if s != nil {
		cc.SetName(*s)
	}
	return cc
}

// AddNumberIDs adds the "number" edge to the Number entity by IDs.
func (cc *CarrierCreate) AddNumberIDs(ids ...int) *CarrierCreate {
	cc.mutation.AddNumberIDs(ids...)
	return cc
}

// AddNumber adds the "number" edges to the Number entity.
func (cc *CarrierCreate) AddNumber(n ...*Number) *CarrierCreate {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return cc.AddNumberIDs(ids...)
}

// Mutation returns the CarrierMutation object of the builder.
func (cc *CarrierCreate) Mutation() *CarrierMutation {
	return cc.mutation
}

// Save creates the Carrier in the database.
func (cc *CarrierCreate) Save(ctx context.Context) (*Carrier, error) {
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *CarrierCreate) SaveX(ctx context.Context) *Carrier {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *CarrierCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *CarrierCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *CarrierCreate) check() error {
	return nil
}

func (cc *CarrierCreate) sqlSave(ctx context.Context) (*Carrier, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *CarrierCreate) createSpec() (*Carrier, *sqlgraph.CreateSpec) {
	var (
		_node = &Carrier{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(carrier.Table, sqlgraph.NewFieldSpec(carrier.FieldID, field.TypeInt))
	)
	if value, ok := cc.mutation.Name(); ok {
		_spec.SetField(carrier.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if nodes := cc.mutation.NumberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carrier.NumberTable,
			Columns: []string{carrier.NumberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(number.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CarrierCreateBulk is the builder for creating many Carrier entities in bulk.
type CarrierCreateBulk struct {
	config
	err      error
	builders []*CarrierCreate
}

// Save creates the Carrier entities in the database.
func (ccb *CarrierCreateBulk) Save(ctx context.Context) ([]*Carrier, error) {
	if ccb.err != nil {
		return nil, ccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Carrier, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CarrierMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *CarrierCreateBulk) SaveX(ctx context.Context) []*Carrier {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *CarrierCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *CarrierCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
