// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/carrier"
)

// Carrier is the model entity for the Carrier schema.
type Carrier struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "Name" field.
	Name string `json:"Name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CarrierQuery when eager-loading is set.
	Edges        CarrierEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CarrierEdges holds the relations/edges for other nodes in the graph.
type CarrierEdges struct {
	// Number holds the value of the number edge.
	Number []*Number `json:"number,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// NumberOrErr returns the Number value or an error if the edge
// was not loaded in eager-loading.
func (e CarrierEdges) NumberOrErr() ([]*Number, error) {
	if e.loadedTypes[0] {
		return e.Number, nil
	}
	return nil, &NotLoadedError{edge: "number"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Carrier) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case carrier.FieldID:
			values[i] = new(sql.NullInt64)
		case carrier.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Carrier fields.
func (c *Carrier) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case carrier.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			c.ID = int(value.Int64)
		case carrier.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Name", values[i])
			} else if value.Valid {
				c.Name = value.String
			}
		default:
			c.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Carrier.
// This includes values selected through modifiers, order, etc.
func (c *Carrier) Value(name string) (ent.Value, error) {
	return c.selectValues.Get(name)
}

// QueryNumber queries the "number" edge of the Carrier entity.
func (c *Carrier) QueryNumber() *NumberQuery {
	return NewCarrierClient(c.config).QueryNumber(c)
}

// Update returns a builder for updating this Carrier.
// Note that you need to call Carrier.Unwrap() before calling this method if this Carrier
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Carrier) Update() *CarrierUpdateOne {
	return NewCarrierClient(c.config).UpdateOne(c)
}

// Unwrap unwraps the Carrier entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (c *Carrier) Unwrap() *Carrier {
	_tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Carrier is not a transactional entity")
	}
	c.config.driver = _tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Carrier) String() string {
	var builder strings.Builder
	builder.WriteString("Carrier(")
	builder.WriteString(fmt.Sprintf("id=%v, ", c.ID))
	builder.WriteString("Name=")
	builder.WriteString(c.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Carriers is a parsable slice of Carrier.
type Carriers []*Carrier
