// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/comment"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/predicate"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/provider"
)

// CommentUpdate is the builder for updating Comment entities.
type CommentUpdate struct {
	config
	hooks    []Hook
	mutation *CommentMutation
}

// Where appends a list predicates to the CommentUpdate builder.
func (cu *CommentUpdate) Where(ps ...predicate.Comment) *CommentUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetPostDate sets the "PostDate" field.
func (cu *CommentUpdate) SetPostDate(t time.Time) *CommentUpdate {
	cu.mutation.SetPostDate(t)
	return cu
}

// SetNillablePostDate sets the "PostDate" field if the given value is not nil.
func (cu *CommentUpdate) SetNillablePostDate(t *time.Time) *CommentUpdate {
	if t != nil {
		cu.SetPostDate(*t)
	}
	return cu
}

// SetCommentText sets the "CommentText" field.
func (cu *CommentUpdate) SetCommentText(s string) *CommentUpdate {
	cu.mutation.SetCommentText(s)
	return cu
}

// SetNillableCommentText sets the "CommentText" field if the given value is not nil.
func (cu *CommentUpdate) SetNillableCommentText(s *string) *CommentUpdate {
	if s != nil {
		cu.SetCommentText(*s)
	}
	return cu
}

// SetCommentFraudScore sets the "CommentFraudScore" field.
func (cu *CommentUpdate) SetCommentFraudScore(i int) *CommentUpdate {
	cu.mutation.ResetCommentFraudScore()
	cu.mutation.SetCommentFraudScore(i)
	return cu
}

// SetNillableCommentFraudScore sets the "CommentFraudScore" field if the given value is not nil.
func (cu *CommentUpdate) SetNillableCommentFraudScore(i *int) *CommentUpdate {
	if i != nil {
		cu.SetCommentFraudScore(*i)
	}
	return cu
}

// AddCommentFraudScore adds i to the "CommentFraudScore" field.
func (cu *CommentUpdate) AddCommentFraudScore(i int) *CommentUpdate {
	cu.mutation.AddCommentFraudScore(i)
	return cu
}

// SetProviderID sets the "provider" edge to the Provider entity by ID.
func (cu *CommentUpdate) SetProviderID(id int) *CommentUpdate {
	cu.mutation.SetProviderID(id)
	return cu
}

// SetProvider sets the "provider" edge to the Provider entity.
func (cu *CommentUpdate) SetProvider(p *Provider) *CommentUpdate {
	return cu.SetProviderID(p.ID)
}

// Mutation returns the CommentMutation object of the builder.
func (cu *CommentUpdate) Mutation() *CommentMutation {
	return cu.mutation
}

// ClearProvider clears the "provider" edge to the Provider entity.
func (cu *CommentUpdate) ClearProvider() *CommentUpdate {
	cu.mutation.ClearProvider()
	return cu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CommentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CommentUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CommentUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CommentUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *CommentUpdate) check() error {
	if cu.mutation.ProviderCleared() && len(cu.mutation.ProviderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Comment.provider"`)
	}
	return nil
}

func (cu *CommentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(comment.Table, comment.Columns, sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.PostDate(); ok {
		_spec.SetField(comment.FieldPostDate, field.TypeTime, value)
	}
	if value, ok := cu.mutation.CommentText(); ok {
		_spec.SetField(comment.FieldCommentText, field.TypeString, value)
	}
	if value, ok := cu.mutation.CommentFraudScore(); ok {
		_spec.SetField(comment.FieldCommentFraudScore, field.TypeInt, value)
	}
	if value, ok := cu.mutation.AddedCommentFraudScore(); ok {
		_spec.AddField(comment.FieldCommentFraudScore, field.TypeInt, value)
	}
	if cu.mutation.ProviderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.ProviderTable,
			Columns: []string{comment.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.ProviderTable,
			Columns: []string{comment.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{comment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// CommentUpdateOne is the builder for updating a single Comment entity.
type CommentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CommentMutation
}

// SetPostDate sets the "PostDate" field.
func (cuo *CommentUpdateOne) SetPostDate(t time.Time) *CommentUpdateOne {
	cuo.mutation.SetPostDate(t)
	return cuo
}

// SetNillablePostDate sets the "PostDate" field if the given value is not nil.
func (cuo *CommentUpdateOne) SetNillablePostDate(t *time.Time) *CommentUpdateOne {
	if t != nil {
		cuo.SetPostDate(*t)
	}
	return cuo
}

// SetCommentText sets the "CommentText" field.
func (cuo *CommentUpdateOne) SetCommentText(s string) *CommentUpdateOne {
	cuo.mutation.SetCommentText(s)
	return cuo
}

// SetNillableCommentText sets the "CommentText" field if the given value is not nil.
func (cuo *CommentUpdateOne) SetNillableCommentText(s *string) *CommentUpdateOne {
	if s != nil {
		cuo.SetCommentText(*s)
	}
	return cuo
}

// SetCommentFraudScore sets the "CommentFraudScore" field.
func (cuo *CommentUpdateOne) SetCommentFraudScore(i int) *CommentUpdateOne {
	cuo.mutation.ResetCommentFraudScore()
	cuo.mutation.SetCommentFraudScore(i)
	return cuo
}

// SetNillableCommentFraudScore sets the "CommentFraudScore" field if the given value is not nil.
func (cuo *CommentUpdateOne) SetNillableCommentFraudScore(i *int) *CommentUpdateOne {
	if i != nil {
		cuo.SetCommentFraudScore(*i)
	}
	return cuo
}

// AddCommentFraudScore adds i to the "CommentFraudScore" field.
func (cuo *CommentUpdateOne) AddCommentFraudScore(i int) *CommentUpdateOne {
	cuo.mutation.AddCommentFraudScore(i)
	return cuo
}

// SetProviderID sets the "provider" edge to the Provider entity by ID.
func (cuo *CommentUpdateOne) SetProviderID(id int) *CommentUpdateOne {
	cuo.mutation.SetProviderID(id)
	return cuo
}

// SetProvider sets the "provider" edge to the Provider entity.
func (cuo *CommentUpdateOne) SetProvider(p *Provider) *CommentUpdateOne {
	return cuo.SetProviderID(p.ID)
}

// Mutation returns the CommentMutation object of the builder.
func (cuo *CommentUpdateOne) Mutation() *CommentMutation {
	return cuo.mutation
}

// ClearProvider clears the "provider" edge to the Provider entity.
func (cuo *CommentUpdateOne) ClearProvider() *CommentUpdateOne {
	cuo.mutation.ClearProvider()
	return cuo
}

// Where appends a list predicates to the CommentUpdate builder.
func (cuo *CommentUpdateOne) Where(ps ...predicate.Comment) *CommentUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CommentUpdateOne) Select(field string, fields ...string) *CommentUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Comment entity.
func (cuo *CommentUpdateOne) Save(ctx context.Context) (*Comment, error) {
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CommentUpdateOne) SaveX(ctx context.Context) *Comment {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CommentUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CommentUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *CommentUpdateOne) check() error {
	if cuo.mutation.ProviderCleared() && len(cuo.mutation.ProviderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Comment.provider"`)
	}
	return nil
}

func (cuo *CommentUpdateOne) sqlSave(ctx context.Context) (_node *Comment, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(comment.Table, comment.Columns, sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Comment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, comment.FieldID)
		for _, f := range fields {
			if !comment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != comment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.PostDate(); ok {
		_spec.SetField(comment.FieldPostDate, field.TypeTime, value)
	}
	if value, ok := cuo.mutation.CommentText(); ok {
		_spec.SetField(comment.FieldCommentText, field.TypeString, value)
	}
	if value, ok := cuo.mutation.CommentFraudScore(); ok {
		_spec.SetField(comment.FieldCommentFraudScore, field.TypeInt, value)
	}
	if value, ok := cuo.mutation.AddedCommentFraudScore(); ok {
		_spec.AddField(comment.FieldCommentFraudScore, field.TypeInt, value)
	}
	if cuo.mutation.ProviderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.ProviderTable,
			Columns: []string{comment.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.ProviderTable,
			Columns: []string{comment.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Comment{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{comment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
