// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/linetype"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/number"
	"github.com/Blanco0420/Phone-Number-Check/backend/providers"
)

// LineTypeCreate is the builder for creating a LineType entity.
type LineTypeCreate struct {
	config
	mutation *LineTypeMutation
	hooks    []Hook
}

// SetLineType sets the "LineType" field.
func (ltc *LineTypeCreate) SetLineType(pt providers.LineType) *LineTypeCreate {
	ltc.mutation.SetLineType(pt)
	return ltc
}

// SetNillableLineType sets the "LineType" field if the given value is not nil.
func (ltc *LineTypeCreate) SetNillableLineType(pt *providers.LineType) *LineTypeCreate {
	if pt != nil {
		ltc.SetLineType(*pt)
	}
	return ltc
}

// AddNumberIDs adds the "number" edge to the Number entity by IDs.
func (ltc *LineTypeCreate) AddNumberIDs(ids ...int) *LineTypeCreate {
	ltc.mutation.AddNumberIDs(ids...)
	return ltc
}

// AddNumber adds the "number" edges to the Number entity.
func (ltc *LineTypeCreate) AddNumber(n ...*Number) *LineTypeCreate {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return ltc.AddNumberIDs(ids...)
}

// Mutation returns the LineTypeMutation object of the builder.
func (ltc *LineTypeCreate) Mutation() *LineTypeMutation {
	return ltc.mutation
}

// Save creates the LineType in the database.
func (ltc *LineTypeCreate) Save(ctx context.Context) (*LineType, error) {
	ltc.defaults()
	return withHooks(ctx, ltc.sqlSave, ltc.mutation, ltc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ltc *LineTypeCreate) SaveX(ctx context.Context) *LineType {
	v, err := ltc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ltc *LineTypeCreate) Exec(ctx context.Context) error {
	_, err := ltc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ltc *LineTypeCreate) ExecX(ctx context.Context) {
	if err := ltc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ltc *LineTypeCreate) defaults() {
	if _, ok := ltc.mutation.LineType(); !ok {
		v := linetype.DefaultLineType
		ltc.mutation.SetLineType(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ltc *LineTypeCreate) check() error {
	if _, ok := ltc.mutation.LineType(); !ok {
		return &ValidationError{Name: "LineType", err: errors.New(`ent: missing required field "LineType.LineType"`)}
	}
	if v, ok := ltc.mutation.LineType(); ok {
		if err := linetype.LineTypeValidator(v); err != nil {
			return &ValidationError{Name: "LineType", err: fmt.Errorf(`ent: validator failed for field "LineType.LineType": %w`, err)}
		}
	}
	return nil
}

func (ltc *LineTypeCreate) sqlSave(ctx context.Context) (*LineType, error) {
	if err := ltc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ltc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ltc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ltc.mutation.id = &_node.ID
	ltc.mutation.done = true
	return _node, nil
}

func (ltc *LineTypeCreate) createSpec() (*LineType, *sqlgraph.CreateSpec) {
	var (
		_node = &LineType{config: ltc.config}
		_spec = sqlgraph.NewCreateSpec(linetype.Table, sqlgraph.NewFieldSpec(linetype.FieldID, field.TypeInt))
	)
	if value, ok := ltc.mutation.LineType(); ok {
		_spec.SetField(linetype.FieldLineType, field.TypeEnum, value)
		_node.LineType = value
	}
	if nodes := ltc.mutation.NumberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   linetype.NumberTable,
			Columns: []string{linetype.NumberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(number.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LineTypeCreateBulk is the builder for creating many LineType entities in bulk.
type LineTypeCreateBulk struct {
	config
	err      error
	builders []*LineTypeCreate
}

// Save creates the LineType entities in the database.
func (ltcb *LineTypeCreateBulk) Save(ctx context.Context) ([]*LineType, error) {
	if ltcb.err != nil {
		return nil, ltcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ltcb.builders))
	nodes := make([]*LineType, len(ltcb.builders))
	mutators := make([]Mutator, len(ltcb.builders))
	for i := range ltcb.builders {
		func(i int, root context.Context) {
			builder := ltcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LineTypeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ltcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ltcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ltcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ltcb *LineTypeCreateBulk) SaveX(ctx context.Context) []*LineType {
	v, err := ltcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ltcb *LineTypeCreateBulk) Exec(ctx context.Context) error {
	_, err := ltcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ltcb *LineTypeCreateBulk) ExecX(ctx context.Context) {
	if err := ltcb.Exec(ctx); err != nil {
		panic(err)
	}
}
