// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/linetype"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/number"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/predicate"
)

// LineTypeQuery is the builder for querying LineType entities.
type LineTypeQuery struct {
	config
	ctx        *QueryContext
	order      []linetype.OrderOption
	inters     []Interceptor
	predicates []predicate.LineType
	withNumber *NumberQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LineTypeQuery builder.
func (ltq *LineTypeQuery) Where(ps ...predicate.LineType) *LineTypeQuery {
	ltq.predicates = append(ltq.predicates, ps...)
	return ltq
}

// Limit the number of records to be returned by this query.
func (ltq *LineTypeQuery) Limit(limit int) *LineTypeQuery {
	ltq.ctx.Limit = &limit
	return ltq
}

// Offset to start from.
func (ltq *LineTypeQuery) Offset(offset int) *LineTypeQuery {
	ltq.ctx.Offset = &offset
	return ltq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ltq *LineTypeQuery) Unique(unique bool) *LineTypeQuery {
	ltq.ctx.Unique = &unique
	return ltq
}

// Order specifies how the records should be ordered.
func (ltq *LineTypeQuery) Order(o ...linetype.OrderOption) *LineTypeQuery {
	ltq.order = append(ltq.order, o...)
	return ltq
}

// QueryNumber chains the current query on the "number" edge.
func (ltq *LineTypeQuery) QueryNumber() *NumberQuery {
	query := (&NumberClient{config: ltq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ltq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ltq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(linetype.Table, linetype.FieldID, selector),
			sqlgraph.To(number.Table, number.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, linetype.NumberTable, linetype.NumberColumn),
		)
		fromU = sqlgraph.SetNeighbors(ltq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first LineType entity from the query.
// Returns a *NotFoundError when no LineType was found.
func (ltq *LineTypeQuery) First(ctx context.Context) (*LineType, error) {
	nodes, err := ltq.Limit(1).All(setContextOp(ctx, ltq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{linetype.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ltq *LineTypeQuery) FirstX(ctx context.Context) *LineType {
	node, err := ltq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LineType ID from the query.
// Returns a *NotFoundError when no LineType ID was found.
func (ltq *LineTypeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ltq.Limit(1).IDs(setContextOp(ctx, ltq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{linetype.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ltq *LineTypeQuery) FirstIDX(ctx context.Context) int {
	id, err := ltq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LineType entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LineType entity is found.
// Returns a *NotFoundError when no LineType entities are found.
func (ltq *LineTypeQuery) Only(ctx context.Context) (*LineType, error) {
	nodes, err := ltq.Limit(2).All(setContextOp(ctx, ltq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{linetype.Label}
	default:
		return nil, &NotSingularError{linetype.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ltq *LineTypeQuery) OnlyX(ctx context.Context) *LineType {
	node, err := ltq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LineType ID in the query.
// Returns a *NotSingularError when more than one LineType ID is found.
// Returns a *NotFoundError when no entities are found.
func (ltq *LineTypeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ltq.Limit(2).IDs(setContextOp(ctx, ltq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{linetype.Label}
	default:
		err = &NotSingularError{linetype.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ltq *LineTypeQuery) OnlyIDX(ctx context.Context) int {
	id, err := ltq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LineTypes.
func (ltq *LineTypeQuery) All(ctx context.Context) ([]*LineType, error) {
	ctx = setContextOp(ctx, ltq.ctx, ent.OpQueryAll)
	if err := ltq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*LineType, *LineTypeQuery]()
	return withInterceptors[[]*LineType](ctx, ltq, qr, ltq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ltq *LineTypeQuery) AllX(ctx context.Context) []*LineType {
	nodes, err := ltq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LineType IDs.
func (ltq *LineTypeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ltq.ctx.Unique == nil && ltq.path != nil {
		ltq.Unique(true)
	}
	ctx = setContextOp(ctx, ltq.ctx, ent.OpQueryIDs)
	if err = ltq.Select(linetype.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ltq *LineTypeQuery) IDsX(ctx context.Context) []int {
	ids, err := ltq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ltq *LineTypeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ltq.ctx, ent.OpQueryCount)
	if err := ltq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ltq, querierCount[*LineTypeQuery](), ltq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ltq *LineTypeQuery) CountX(ctx context.Context) int {
	count, err := ltq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ltq *LineTypeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ltq.ctx, ent.OpQueryExist)
	switch _, err := ltq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ltq *LineTypeQuery) ExistX(ctx context.Context) bool {
	exist, err := ltq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LineTypeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ltq *LineTypeQuery) Clone() *LineTypeQuery {
	if ltq == nil {
		return nil
	}
	return &LineTypeQuery{
		config:     ltq.config,
		ctx:        ltq.ctx.Clone(),
		order:      append([]linetype.OrderOption{}, ltq.order...),
		inters:     append([]Interceptor{}, ltq.inters...),
		predicates: append([]predicate.LineType{}, ltq.predicates...),
		withNumber: ltq.withNumber.Clone(),
		// clone intermediate query.
		sql:  ltq.sql.Clone(),
		path: ltq.path,
	}
}

// WithNumber tells the query-builder to eager-load the nodes that are connected to
// the "number" edge. The optional arguments are used to configure the query builder of the edge.
func (ltq *LineTypeQuery) WithNumber(opts ...func(*NumberQuery)) *LineTypeQuery {
	query := (&NumberClient{config: ltq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ltq.withNumber = query
	return ltq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		LineType providers.LineType `json:"LineType,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LineType.Query().
//		GroupBy(linetype.FieldLineType).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ltq *LineTypeQuery) GroupBy(field string, fields ...string) *LineTypeGroupBy {
	ltq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LineTypeGroupBy{build: ltq}
	grbuild.flds = &ltq.ctx.Fields
	grbuild.label = linetype.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		LineType providers.LineType `json:"LineType,omitempty"`
//	}
//
//	client.LineType.Query().
//		Select(linetype.FieldLineType).
//		Scan(ctx, &v)
func (ltq *LineTypeQuery) Select(fields ...string) *LineTypeSelect {
	ltq.ctx.Fields = append(ltq.ctx.Fields, fields...)
	sbuild := &LineTypeSelect{LineTypeQuery: ltq}
	sbuild.label = linetype.Label
	sbuild.flds, sbuild.scan = &ltq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LineTypeSelect configured with the given aggregations.
func (ltq *LineTypeQuery) Aggregate(fns ...AggregateFunc) *LineTypeSelect {
	return ltq.Select().Aggregate(fns...)
}

func (ltq *LineTypeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ltq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ltq); err != nil {
				return err
			}
		}
	}
	for _, f := range ltq.ctx.Fields {
		if !linetype.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ltq.path != nil {
		prev, err := ltq.path(ctx)
		if err != nil {
			return err
		}
		ltq.sql = prev
	}
	return nil
}

func (ltq *LineTypeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*LineType, error) {
	var (
		nodes       = []*LineType{}
		_spec       = ltq.querySpec()
		loadedTypes = [1]bool{
			ltq.withNumber != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*LineType).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &LineType{config: ltq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ltq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ltq.withNumber; query != nil {
		if err := ltq.loadNumber(ctx, query, nodes,
			func(n *LineType) { n.Edges.Number = []*Number{} },
			func(n *LineType, e *Number) { n.Edges.Number = append(n.Edges.Number, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ltq *LineTypeQuery) loadNumber(ctx context.Context, query *NumberQuery, nodes []*LineType, init func(*LineType), assign func(*LineType, *Number)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*LineType)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Number(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(linetype.NumberColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.line_type_number
		if fk == nil {
			return fmt.Errorf(`foreign-key "line_type_number" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "line_type_number" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (ltq *LineTypeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ltq.querySpec()
	_spec.Node.Columns = ltq.ctx.Fields
	if len(ltq.ctx.Fields) > 0 {
		_spec.Unique = ltq.ctx.Unique != nil && *ltq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ltq.driver, _spec)
}

func (ltq *LineTypeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(linetype.Table, linetype.Columns, sqlgraph.NewFieldSpec(linetype.FieldID, field.TypeInt))
	_spec.From = ltq.sql
	if unique := ltq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ltq.path != nil {
		_spec.Unique = true
	}
	if fields := ltq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, linetype.FieldID)
		for i := range fields {
			if fields[i] != linetype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ltq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ltq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ltq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ltq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ltq *LineTypeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ltq.driver.Dialect())
	t1 := builder.Table(linetype.Table)
	columns := ltq.ctx.Fields
	if len(columns) == 0 {
		columns = linetype.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ltq.sql != nil {
		selector = ltq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ltq.ctx.Unique != nil && *ltq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ltq.predicates {
		p(selector)
	}
	for _, p := range ltq.order {
		p(selector)
	}
	if offset := ltq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ltq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LineTypeGroupBy is the group-by builder for LineType entities.
type LineTypeGroupBy struct {
	selector
	build *LineTypeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ltgb *LineTypeGroupBy) Aggregate(fns ...AggregateFunc) *LineTypeGroupBy {
	ltgb.fns = append(ltgb.fns, fns...)
	return ltgb
}

// Scan applies the selector query and scans the result into the given value.
func (ltgb *LineTypeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ltgb.build.ctx, ent.OpQueryGroupBy)
	if err := ltgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LineTypeQuery, *LineTypeGroupBy](ctx, ltgb.build, ltgb, ltgb.build.inters, v)
}

func (ltgb *LineTypeGroupBy) sqlScan(ctx context.Context, root *LineTypeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ltgb.fns))
	for _, fn := range ltgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ltgb.flds)+len(ltgb.fns))
		for _, f := range *ltgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ltgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ltgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LineTypeSelect is the builder for selecting fields of LineType entities.
type LineTypeSelect struct {
	*LineTypeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (lts *LineTypeSelect) Aggregate(fns ...AggregateFunc) *LineTypeSelect {
	lts.fns = append(lts.fns, fns...)
	return lts
}

// Scan applies the selector query and scans the result into the given value.
func (lts *LineTypeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lts.ctx, ent.OpQuerySelect)
	if err := lts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LineTypeQuery, *LineTypeSelect](ctx, lts.LineTypeQuery, lts, lts.inters, v)
}

func (lts *LineTypeSelect) sqlScan(ctx context.Context, root *LineTypeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(lts.fns))
	for _, fn := range lts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*lts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
