// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/linetype"
	"github.com/Blanco0420/Phone-Number-Check/backend/providers"
)

// LineType is the model entity for the LineType schema.
type LineType struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// LineType holds the value of the "LineType" field.
	LineType providers.LineType `json:"LineType,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LineTypeQuery when eager-loading is set.
	Edges        LineTypeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// LineTypeEdges holds the relations/edges for other nodes in the graph.
type LineTypeEdges struct {
	// Number holds the value of the number edge.
	Number []*Number `json:"number,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// NumberOrErr returns the Number value or an error if the edge
// was not loaded in eager-loading.
func (e LineTypeEdges) NumberOrErr() ([]*Number, error) {
	if e.loadedTypes[0] {
		return e.Number, nil
	}
	return nil, &NotLoadedError{edge: "number"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LineType) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case linetype.FieldID:
			values[i] = new(sql.NullInt64)
		case linetype.FieldLineType:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LineType fields.
func (lt *LineType) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case linetype.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			lt.ID = int(value.Int64)
		case linetype.FieldLineType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field LineType", values[i])
			} else if value.Valid {
				lt.LineType = providers.LineType(value.String)
			}
		default:
			lt.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LineType.
// This includes values selected through modifiers, order, etc.
func (lt *LineType) Value(name string) (ent.Value, error) {
	return lt.selectValues.Get(name)
}

// QueryNumber queries the "number" edge of the LineType entity.
func (lt *LineType) QueryNumber() *NumberQuery {
	return NewLineTypeClient(lt.config).QueryNumber(lt)
}

// Update returns a builder for updating this LineType.
// Note that you need to call LineType.Unwrap() before calling this method if this LineType
// was returned from a transaction, and the transaction was committed or rolled back.
func (lt *LineType) Update() *LineTypeUpdateOne {
	return NewLineTypeClient(lt.config).UpdateOne(lt)
}

// Unwrap unwraps the LineType entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (lt *LineType) Unwrap() *LineType {
	_tx, ok := lt.config.driver.(*txDriver)
	if !ok {
		panic("ent: LineType is not a transactional entity")
	}
	lt.config.driver = _tx.drv
	return lt
}

// String implements the fmt.Stringer.
func (lt *LineType) String() string {
	var builder strings.Builder
	builder.WriteString("LineType(")
	builder.WriteString(fmt.Sprintf("id=%v, ", lt.ID))
	builder.WriteString("LineType=")
	builder.WriteString(fmt.Sprintf("%v", lt.LineType))
	builder.WriteByte(')')
	return builder.String()
}

// LineTypes is a parsable slice of LineType.
type LineTypes []*LineType
