// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/caller"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/carrier"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/linetype"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/number"
)

// Number is the model entity for the Number schema.
type Number struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Number holds the value of the "Number" field.
	Number string `json:"Number,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NumberQuery when eager-loading is set.
	Edges            NumberEdges `json:"edges"`
	caller_number    *int
	carrier_number   *int
	line_type_number *int
	selectValues     sql.SelectValues
}

// NumberEdges holds the relations/edges for other nodes in the graph.
type NumberEdges struct {
	// Caller holds the value of the caller edge.
	Caller *Caller `json:"caller,omitempty"`
	// Linetype holds the value of the linetype edge.
	Linetype *LineType `json:"linetype,omitempty"`
	// Carrier holds the value of the carrier edge.
	Carrier *Carrier `json:"carrier,omitempty"`
	// Provider holds the value of the provider edge.
	Provider []*Provider `json:"provider,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// CallerOrErr returns the Caller value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NumberEdges) CallerOrErr() (*Caller, error) {
	if e.Caller != nil {
		return e.Caller, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: caller.Label}
	}
	return nil, &NotLoadedError{edge: "caller"}
}

// LinetypeOrErr returns the Linetype value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NumberEdges) LinetypeOrErr() (*LineType, error) {
	if e.Linetype != nil {
		return e.Linetype, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: linetype.Label}
	}
	return nil, &NotLoadedError{edge: "linetype"}
}

// CarrierOrErr returns the Carrier value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NumberEdges) CarrierOrErr() (*Carrier, error) {
	if e.Carrier != nil {
		return e.Carrier, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: carrier.Label}
	}
	return nil, &NotLoadedError{edge: "carrier"}
}

// ProviderOrErr returns the Provider value or an error if the edge
// was not loaded in eager-loading.
func (e NumberEdges) ProviderOrErr() ([]*Provider, error) {
	if e.loadedTypes[3] {
		return e.Provider, nil
	}
	return nil, &NotLoadedError{edge: "provider"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Number) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case number.FieldID:
			values[i] = new(sql.NullInt64)
		case number.FieldNumber:
			values[i] = new(sql.NullString)
		case number.ForeignKeys[0]: // caller_number
			values[i] = new(sql.NullInt64)
		case number.ForeignKeys[1]: // carrier_number
			values[i] = new(sql.NullInt64)
		case number.ForeignKeys[2]: // line_type_number
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Number fields.
func (n *Number) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case number.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			n.ID = int(value.Int64)
		case number.FieldNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Number", values[i])
			} else if value.Valid {
				n.Number = value.String
			}
		case number.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field caller_number", value)
			} else if value.Valid {
				n.caller_number = new(int)
				*n.caller_number = int(value.Int64)
			}
		case number.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field carrier_number", value)
			} else if value.Valid {
				n.carrier_number = new(int)
				*n.carrier_number = int(value.Int64)
			}
		case number.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field line_type_number", value)
			} else if value.Valid {
				n.line_type_number = new(int)
				*n.line_type_number = int(value.Int64)
			}
		default:
			n.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Number.
// This includes values selected through modifiers, order, etc.
func (n *Number) Value(name string) (ent.Value, error) {
	return n.selectValues.Get(name)
}

// QueryCaller queries the "caller" edge of the Number entity.
func (n *Number) QueryCaller() *CallerQuery {
	return NewNumberClient(n.config).QueryCaller(n)
}

// QueryLinetype queries the "linetype" edge of the Number entity.
func (n *Number) QueryLinetype() *LineTypeQuery {
	return NewNumberClient(n.config).QueryLinetype(n)
}

// QueryCarrier queries the "carrier" edge of the Number entity.
func (n *Number) QueryCarrier() *CarrierQuery {
	return NewNumberClient(n.config).QueryCarrier(n)
}

// QueryProvider queries the "provider" edge of the Number entity.
func (n *Number) QueryProvider() *ProviderQuery {
	return NewNumberClient(n.config).QueryProvider(n)
}

// Update returns a builder for updating this Number.
// Note that you need to call Number.Unwrap() before calling this method if this Number
// was returned from a transaction, and the transaction was committed or rolled back.
func (n *Number) Update() *NumberUpdateOne {
	return NewNumberClient(n.config).UpdateOne(n)
}

// Unwrap unwraps the Number entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (n *Number) Unwrap() *Number {
	_tx, ok := n.config.driver.(*txDriver)
	if !ok {
		panic("ent: Number is not a transactional entity")
	}
	n.config.driver = _tx.drv
	return n
}

// String implements the fmt.Stringer.
func (n *Number) String() string {
	var builder strings.Builder
	builder.WriteString("Number(")
	builder.WriteString(fmt.Sprintf("id=%v, ", n.ID))
	builder.WriteString("Number=")
	builder.WriteString(n.Number)
	builder.WriteByte(')')
	return builder.String()
}

// Numbers is a parsable slice of Number.
type Numbers []*Number
