// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/caller"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/carrier"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/linetype"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/number"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/provider"
)

// NumberCreate is the builder for creating a Number entity.
type NumberCreate struct {
	config
	mutation *NumberMutation
	hooks    []Hook
}

// SetNumber sets the "Number" field.
func (nc *NumberCreate) SetNumber(s string) *NumberCreate {
	nc.mutation.SetNumber(s)
	return nc
}

// SetCallerID sets the "caller" edge to the Caller entity by ID.
func (nc *NumberCreate) SetCallerID(id int) *NumberCreate {
	nc.mutation.SetCallerID(id)
	return nc
}

// SetCaller sets the "caller" edge to the Caller entity.
func (nc *NumberCreate) SetCaller(c *Caller) *NumberCreate {
	return nc.SetCallerID(c.ID)
}

// SetLinetypeID sets the "linetype" edge to the LineType entity by ID.
func (nc *NumberCreate) SetLinetypeID(id int) *NumberCreate {
	nc.mutation.SetLinetypeID(id)
	return nc
}

// SetLinetype sets the "linetype" edge to the LineType entity.
func (nc *NumberCreate) SetLinetype(l *LineType) *NumberCreate {
	return nc.SetLinetypeID(l.ID)
}

// SetCarrierID sets the "carrier" edge to the Carrier entity by ID.
func (nc *NumberCreate) SetCarrierID(id int) *NumberCreate {
	nc.mutation.SetCarrierID(id)
	return nc
}

// SetNillableCarrierID sets the "carrier" edge to the Carrier entity by ID if the given value is not nil.
func (nc *NumberCreate) SetNillableCarrierID(id *int) *NumberCreate {
	if id != nil {
		nc = nc.SetCarrierID(*id)
	}
	return nc
}

// SetCarrier sets the "carrier" edge to the Carrier entity.
func (nc *NumberCreate) SetCarrier(c *Carrier) *NumberCreate {
	return nc.SetCarrierID(c.ID)
}

// AddProviderIDs adds the "provider" edge to the Provider entity by IDs.
func (nc *NumberCreate) AddProviderIDs(ids ...int) *NumberCreate {
	nc.mutation.AddProviderIDs(ids...)
	return nc
}

// AddProvider adds the "provider" edges to the Provider entity.
func (nc *NumberCreate) AddProvider(p ...*Provider) *NumberCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return nc.AddProviderIDs(ids...)
}

// Mutation returns the NumberMutation object of the builder.
func (nc *NumberCreate) Mutation() *NumberMutation {
	return nc.mutation
}

// Save creates the Number in the database.
func (nc *NumberCreate) Save(ctx context.Context) (*Number, error) {
	return withHooks(ctx, nc.sqlSave, nc.mutation, nc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (nc *NumberCreate) SaveX(ctx context.Context) *Number {
	v, err := nc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (nc *NumberCreate) Exec(ctx context.Context) error {
	_, err := nc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nc *NumberCreate) ExecX(ctx context.Context) {
	if err := nc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nc *NumberCreate) check() error {
	if _, ok := nc.mutation.Number(); !ok {
		return &ValidationError{Name: "Number", err: errors.New(`ent: missing required field "Number.Number"`)}
	}
	if len(nc.mutation.CallerIDs()) == 0 {
		return &ValidationError{Name: "caller", err: errors.New(`ent: missing required edge "Number.caller"`)}
	}
	if len(nc.mutation.LinetypeIDs()) == 0 {
		return &ValidationError{Name: "linetype", err: errors.New(`ent: missing required edge "Number.linetype"`)}
	}
	return nil
}

func (nc *NumberCreate) sqlSave(ctx context.Context) (*Number, error) {
	if err := nc.check(); err != nil {
		return nil, err
	}
	_node, _spec := nc.createSpec()
	if err := sqlgraph.CreateNode(ctx, nc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	nc.mutation.id = &_node.ID
	nc.mutation.done = true
	return _node, nil
}

func (nc *NumberCreate) createSpec() (*Number, *sqlgraph.CreateSpec) {
	var (
		_node = &Number{config: nc.config}
		_spec = sqlgraph.NewCreateSpec(number.Table, sqlgraph.NewFieldSpec(number.FieldID, field.TypeInt))
	)
	if value, ok := nc.mutation.Number(); ok {
		_spec.SetField(number.FieldNumber, field.TypeString, value)
		_node.Number = value
	}
	if nodes := nc.mutation.CallerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   number.CallerTable,
			Columns: []string{number.CallerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(caller.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.caller_number = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := nc.mutation.LinetypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   number.LinetypeTable,
			Columns: []string{number.LinetypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linetype.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.line_type_number = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := nc.mutation.CarrierIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   number.CarrierTable,
			Columns: []string{number.CarrierColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(carrier.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.carrier_number = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := nc.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   number.ProviderTable,
			Columns: []string{number.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// NumberCreateBulk is the builder for creating many Number entities in bulk.
type NumberCreateBulk struct {
	config
	err      error
	builders []*NumberCreate
}

// Save creates the Number entities in the database.
func (ncb *NumberCreateBulk) Save(ctx context.Context) ([]*Number, error) {
	if ncb.err != nil {
		return nil, ncb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ncb.builders))
	nodes := make([]*Number, len(ncb.builders))
	mutators := make([]Mutator, len(ncb.builders))
	for i := range ncb.builders {
		func(i int, root context.Context) {
			builder := ncb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NumberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ncb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ncb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ncb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ncb *NumberCreateBulk) SaveX(ctx context.Context) []*Number {
	v, err := ncb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ncb *NumberCreateBulk) Exec(ctx context.Context) error {
	_, err := ncb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ncb *NumberCreateBulk) ExecX(ctx context.Context) {
	if err := ncb.Exec(ctx); err != nil {
		panic(err)
	}
}
