// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/caller"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/carrier"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/linetype"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/number"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/predicate"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/provider"
)

// NumberUpdate is the builder for updating Number entities.
type NumberUpdate struct {
	config
	hooks    []Hook
	mutation *NumberMutation
}

// Where appends a list predicates to the NumberUpdate builder.
func (nu *NumberUpdate) Where(ps ...predicate.Number) *NumberUpdate {
	nu.mutation.Where(ps...)
	return nu
}

// SetNumber sets the "Number" field.
func (nu *NumberUpdate) SetNumber(s string) *NumberUpdate {
	nu.mutation.SetNumber(s)
	return nu
}

// SetNillableNumber sets the "Number" field if the given value is not nil.
func (nu *NumberUpdate) SetNillableNumber(s *string) *NumberUpdate {
	if s != nil {
		nu.SetNumber(*s)
	}
	return nu
}

// SetCallerID sets the "caller" edge to the Caller entity by ID.
func (nu *NumberUpdate) SetCallerID(id int) *NumberUpdate {
	nu.mutation.SetCallerID(id)
	return nu
}

// SetCaller sets the "caller" edge to the Caller entity.
func (nu *NumberUpdate) SetCaller(c *Caller) *NumberUpdate {
	return nu.SetCallerID(c.ID)
}

// SetLinetypeID sets the "linetype" edge to the LineType entity by ID.
func (nu *NumberUpdate) SetLinetypeID(id int) *NumberUpdate {
	nu.mutation.SetLinetypeID(id)
	return nu
}

// SetLinetype sets the "linetype" edge to the LineType entity.
func (nu *NumberUpdate) SetLinetype(l *LineType) *NumberUpdate {
	return nu.SetLinetypeID(l.ID)
}

// SetCarrierID sets the "carrier" edge to the Carrier entity by ID.
func (nu *NumberUpdate) SetCarrierID(id int) *NumberUpdate {
	nu.mutation.SetCarrierID(id)
	return nu
}

// SetNillableCarrierID sets the "carrier" edge to the Carrier entity by ID if the given value is not nil.
func (nu *NumberUpdate) SetNillableCarrierID(id *int) *NumberUpdate {
	if id != nil {
		nu = nu.SetCarrierID(*id)
	}
	return nu
}

// SetCarrier sets the "carrier" edge to the Carrier entity.
func (nu *NumberUpdate) SetCarrier(c *Carrier) *NumberUpdate {
	return nu.SetCarrierID(c.ID)
}

// AddProviderIDs adds the "provider" edge to the Provider entity by IDs.
func (nu *NumberUpdate) AddProviderIDs(ids ...int) *NumberUpdate {
	nu.mutation.AddProviderIDs(ids...)
	return nu
}

// AddProvider adds the "provider" edges to the Provider entity.
func (nu *NumberUpdate) AddProvider(p ...*Provider) *NumberUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return nu.AddProviderIDs(ids...)
}

// Mutation returns the NumberMutation object of the builder.
func (nu *NumberUpdate) Mutation() *NumberMutation {
	return nu.mutation
}

// ClearCaller clears the "caller" edge to the Caller entity.
func (nu *NumberUpdate) ClearCaller() *NumberUpdate {
	nu.mutation.ClearCaller()
	return nu
}

// ClearLinetype clears the "linetype" edge to the LineType entity.
func (nu *NumberUpdate) ClearLinetype() *NumberUpdate {
	nu.mutation.ClearLinetype()
	return nu
}

// ClearCarrier clears the "carrier" edge to the Carrier entity.
func (nu *NumberUpdate) ClearCarrier() *NumberUpdate {
	nu.mutation.ClearCarrier()
	return nu
}

// ClearProvider clears all "provider" edges to the Provider entity.
func (nu *NumberUpdate) ClearProvider() *NumberUpdate {
	nu.mutation.ClearProvider()
	return nu
}

// RemoveProviderIDs removes the "provider" edge to Provider entities by IDs.
func (nu *NumberUpdate) RemoveProviderIDs(ids ...int) *NumberUpdate {
	nu.mutation.RemoveProviderIDs(ids...)
	return nu
}

// RemoveProvider removes "provider" edges to Provider entities.
func (nu *NumberUpdate) RemoveProvider(p ...*Provider) *NumberUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return nu.RemoveProviderIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (nu *NumberUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, nu.sqlSave, nu.mutation, nu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (nu *NumberUpdate) SaveX(ctx context.Context) int {
	affected, err := nu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (nu *NumberUpdate) Exec(ctx context.Context) error {
	_, err := nu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nu *NumberUpdate) ExecX(ctx context.Context) {
	if err := nu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nu *NumberUpdate) check() error {
	if nu.mutation.CallerCleared() && len(nu.mutation.CallerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Number.caller"`)
	}
	if nu.mutation.LinetypeCleared() && len(nu.mutation.LinetypeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Number.linetype"`)
	}
	return nil
}

func (nu *NumberUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := nu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(number.Table, number.Columns, sqlgraph.NewFieldSpec(number.FieldID, field.TypeInt))
	if ps := nu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nu.mutation.Number(); ok {
		_spec.SetField(number.FieldNumber, field.TypeString, value)
	}
	if nu.mutation.CallerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   number.CallerTable,
			Columns: []string{number.CallerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(caller.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nu.mutation.CallerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   number.CallerTable,
			Columns: []string{number.CallerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(caller.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nu.mutation.LinetypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   number.LinetypeTable,
			Columns: []string{number.LinetypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linetype.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nu.mutation.LinetypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   number.LinetypeTable,
			Columns: []string{number.LinetypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linetype.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nu.mutation.CarrierCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   number.CarrierTable,
			Columns: []string{number.CarrierColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(carrier.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nu.mutation.CarrierIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   number.CarrierTable,
			Columns: []string{number.CarrierColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(carrier.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nu.mutation.ProviderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   number.ProviderTable,
			Columns: []string{number.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nu.mutation.RemovedProviderIDs(); len(nodes) > 0 && !nu.mutation.ProviderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   number.ProviderTable,
			Columns: []string{number.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nu.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   number.ProviderTable,
			Columns: []string{number.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, nu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{number.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	nu.mutation.done = true
	return n, nil
}

// NumberUpdateOne is the builder for updating a single Number entity.
type NumberUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NumberMutation
}

// SetNumber sets the "Number" field.
func (nuo *NumberUpdateOne) SetNumber(s string) *NumberUpdateOne {
	nuo.mutation.SetNumber(s)
	return nuo
}

// SetNillableNumber sets the "Number" field if the given value is not nil.
func (nuo *NumberUpdateOne) SetNillableNumber(s *string) *NumberUpdateOne {
	if s != nil {
		nuo.SetNumber(*s)
	}
	return nuo
}

// SetCallerID sets the "caller" edge to the Caller entity by ID.
func (nuo *NumberUpdateOne) SetCallerID(id int) *NumberUpdateOne {
	nuo.mutation.SetCallerID(id)
	return nuo
}

// SetCaller sets the "caller" edge to the Caller entity.
func (nuo *NumberUpdateOne) SetCaller(c *Caller) *NumberUpdateOne {
	return nuo.SetCallerID(c.ID)
}

// SetLinetypeID sets the "linetype" edge to the LineType entity by ID.
func (nuo *NumberUpdateOne) SetLinetypeID(id int) *NumberUpdateOne {
	nuo.mutation.SetLinetypeID(id)
	return nuo
}

// SetLinetype sets the "linetype" edge to the LineType entity.
func (nuo *NumberUpdateOne) SetLinetype(l *LineType) *NumberUpdateOne {
	return nuo.SetLinetypeID(l.ID)
}

// SetCarrierID sets the "carrier" edge to the Carrier entity by ID.
func (nuo *NumberUpdateOne) SetCarrierID(id int) *NumberUpdateOne {
	nuo.mutation.SetCarrierID(id)
	return nuo
}

// SetNillableCarrierID sets the "carrier" edge to the Carrier entity by ID if the given value is not nil.
func (nuo *NumberUpdateOne) SetNillableCarrierID(id *int) *NumberUpdateOne {
	if id != nil {
		nuo = nuo.SetCarrierID(*id)
	}
	return nuo
}

// SetCarrier sets the "carrier" edge to the Carrier entity.
func (nuo *NumberUpdateOne) SetCarrier(c *Carrier) *NumberUpdateOne {
	return nuo.SetCarrierID(c.ID)
}

// AddProviderIDs adds the "provider" edge to the Provider entity by IDs.
func (nuo *NumberUpdateOne) AddProviderIDs(ids ...int) *NumberUpdateOne {
	nuo.mutation.AddProviderIDs(ids...)
	return nuo
}

// AddProvider adds the "provider" edges to the Provider entity.
func (nuo *NumberUpdateOne) AddProvider(p ...*Provider) *NumberUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return nuo.AddProviderIDs(ids...)
}

// Mutation returns the NumberMutation object of the builder.
func (nuo *NumberUpdateOne) Mutation() *NumberMutation {
	return nuo.mutation
}

// ClearCaller clears the "caller" edge to the Caller entity.
func (nuo *NumberUpdateOne) ClearCaller() *NumberUpdateOne {
	nuo.mutation.ClearCaller()
	return nuo
}

// ClearLinetype clears the "linetype" edge to the LineType entity.
func (nuo *NumberUpdateOne) ClearLinetype() *NumberUpdateOne {
	nuo.mutation.ClearLinetype()
	return nuo
}

// ClearCarrier clears the "carrier" edge to the Carrier entity.
func (nuo *NumberUpdateOne) ClearCarrier() *NumberUpdateOne {
	nuo.mutation.ClearCarrier()
	return nuo
}

// ClearProvider clears all "provider" edges to the Provider entity.
func (nuo *NumberUpdateOne) ClearProvider() *NumberUpdateOne {
	nuo.mutation.ClearProvider()
	return nuo
}

// RemoveProviderIDs removes the "provider" edge to Provider entities by IDs.
func (nuo *NumberUpdateOne) RemoveProviderIDs(ids ...int) *NumberUpdateOne {
	nuo.mutation.RemoveProviderIDs(ids...)
	return nuo
}

// RemoveProvider removes "provider" edges to Provider entities.
func (nuo *NumberUpdateOne) RemoveProvider(p ...*Provider) *NumberUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return nuo.RemoveProviderIDs(ids...)
}

// Where appends a list predicates to the NumberUpdate builder.
func (nuo *NumberUpdateOne) Where(ps ...predicate.Number) *NumberUpdateOne {
	nuo.mutation.Where(ps...)
	return nuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (nuo *NumberUpdateOne) Select(field string, fields ...string) *NumberUpdateOne {
	nuo.fields = append([]string{field}, fields...)
	return nuo
}

// Save executes the query and returns the updated Number entity.
func (nuo *NumberUpdateOne) Save(ctx context.Context) (*Number, error) {
	return withHooks(ctx, nuo.sqlSave, nuo.mutation, nuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (nuo *NumberUpdateOne) SaveX(ctx context.Context) *Number {
	node, err := nuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (nuo *NumberUpdateOne) Exec(ctx context.Context) error {
	_, err := nuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nuo *NumberUpdateOne) ExecX(ctx context.Context) {
	if err := nuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nuo *NumberUpdateOne) check() error {
	if nuo.mutation.CallerCleared() && len(nuo.mutation.CallerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Number.caller"`)
	}
	if nuo.mutation.LinetypeCleared() && len(nuo.mutation.LinetypeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Number.linetype"`)
	}
	return nil
}

func (nuo *NumberUpdateOne) sqlSave(ctx context.Context) (_node *Number, err error) {
	if err := nuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(number.Table, number.Columns, sqlgraph.NewFieldSpec(number.FieldID, field.TypeInt))
	id, ok := nuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Number.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := nuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, number.FieldID)
		for _, f := range fields {
			if !number.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != number.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := nuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nuo.mutation.Number(); ok {
		_spec.SetField(number.FieldNumber, field.TypeString, value)
	}
	if nuo.mutation.CallerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   number.CallerTable,
			Columns: []string{number.CallerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(caller.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nuo.mutation.CallerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   number.CallerTable,
			Columns: []string{number.CallerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(caller.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nuo.mutation.LinetypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   number.LinetypeTable,
			Columns: []string{number.LinetypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linetype.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nuo.mutation.LinetypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   number.LinetypeTable,
			Columns: []string{number.LinetypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linetype.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nuo.mutation.CarrierCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   number.CarrierTable,
			Columns: []string{number.CarrierColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(carrier.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nuo.mutation.CarrierIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   number.CarrierTable,
			Columns: []string{number.CarrierColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(carrier.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nuo.mutation.ProviderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   number.ProviderTable,
			Columns: []string{number.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nuo.mutation.RemovedProviderIDs(); len(nodes) > 0 && !nuo.mutation.ProviderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   number.ProviderTable,
			Columns: []string{number.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nuo.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   number.ProviderTable,
			Columns: []string{number.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Number{config: nuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, nuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{number.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	nuo.mutation.done = true
	return _node, nil
}
