// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/business"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/number"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/provider"
)

// Provider is the model entity for the Provider schema.
type Provider struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "Name" field.
	Name string `json:"Name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProviderQuery when eager-loading is set.
	Edges           ProviderEdges `json:"edges"`
	number_provider *int
	selectValues    sql.SelectValues
}

// ProviderEdges holds the relations/edges for other nodes in the graph.
type ProviderEdges struct {
	// Number holds the value of the number edge.
	Number *Number `json:"number,omitempty"`
	// Comment holds the value of the comment edge.
	Comment []*Comment `json:"comment,omitempty"`
	// Business holds the value of the business edge.
	Business *Business `json:"business,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// NumberOrErr returns the Number value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProviderEdges) NumberOrErr() (*Number, error) {
	if e.Number != nil {
		return e.Number, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: number.Label}
	}
	return nil, &NotLoadedError{edge: "number"}
}

// CommentOrErr returns the Comment value or an error if the edge
// was not loaded in eager-loading.
func (e ProviderEdges) CommentOrErr() ([]*Comment, error) {
	if e.loadedTypes[1] {
		return e.Comment, nil
	}
	return nil, &NotLoadedError{edge: "comment"}
}

// BusinessOrErr returns the Business value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProviderEdges) BusinessOrErr() (*Business, error) {
	if e.Business != nil {
		return e.Business, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: business.Label}
	}
	return nil, &NotLoadedError{edge: "business"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Provider) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case provider.FieldID:
			values[i] = new(sql.NullInt64)
		case provider.FieldName:
			values[i] = new(sql.NullString)
		case provider.ForeignKeys[0]: // number_provider
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Provider fields.
func (pr *Provider) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case provider.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pr.ID = int(value.Int64)
		case provider.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Name", values[i])
			} else if value.Valid {
				pr.Name = value.String
			}
		case provider.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field number_provider", value)
			} else if value.Valid {
				pr.number_provider = new(int)
				*pr.number_provider = int(value.Int64)
			}
		default:
			pr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Provider.
// This includes values selected through modifiers, order, etc.
func (pr *Provider) Value(name string) (ent.Value, error) {
	return pr.selectValues.Get(name)
}

// QueryNumber queries the "number" edge of the Provider entity.
func (pr *Provider) QueryNumber() *NumberQuery {
	return NewProviderClient(pr.config).QueryNumber(pr)
}

// QueryComment queries the "comment" edge of the Provider entity.
func (pr *Provider) QueryComment() *CommentQuery {
	return NewProviderClient(pr.config).QueryComment(pr)
}

// QueryBusiness queries the "business" edge of the Provider entity.
func (pr *Provider) QueryBusiness() *BusinessQuery {
	return NewProviderClient(pr.config).QueryBusiness(pr)
}

// Update returns a builder for updating this Provider.
// Note that you need to call Provider.Unwrap() before calling this method if this Provider
// was returned from a transaction, and the transaction was committed or rolled back.
func (pr *Provider) Update() *ProviderUpdateOne {
	return NewProviderClient(pr.config).UpdateOne(pr)
}

// Unwrap unwraps the Provider entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pr *Provider) Unwrap() *Provider {
	_tx, ok := pr.config.driver.(*txDriver)
	if !ok {
		panic("ent: Provider is not a transactional entity")
	}
	pr.config.driver = _tx.drv
	return pr
}

// String implements the fmt.Stringer.
func (pr *Provider) String() string {
	var builder strings.Builder
	builder.WriteString("Provider(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pr.ID))
	builder.WriteString("Name=")
	builder.WriteString(pr.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Providers is a parsable slice of Provider.
type Providers []*Provider
