// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/comment"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescCommentFraudScore is the schema descriptor for CommentFraudScore field.
	commentDescCommentFraudScore := commentFields[2].Descriptor()
	// comment.DefaultCommentFraudScore holds the default value on creation for the CommentFraudScore field.
	comment.DefaultCommentFraudScore = commentDescCommentFraudScore.Default.(int)
	linetypeFields := schema.LineType{}.Fields()
	_ = linetypeFields
}
