// Code generated by ent, DO NOT EDIT.

package number

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the number type in the database.
	Label = "number"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNumber holds the string denoting the number field in the database.
	FieldNumber = "number"
	// EdgeCaller holds the string denoting the caller edge name in mutations.
	EdgeCaller = "caller"
	// EdgeLinetype holds the string denoting the linetype edge name in mutations.
	EdgeLinetype = "linetype"
	// EdgeCarrier holds the string denoting the carrier edge name in mutations.
	EdgeCarrier = "carrier"
	// EdgeProvider holds the string denoting the provider edge name in mutations.
	EdgeProvider = "provider"
	// Table holds the table name of the number in the database.
	Table = "numbers"
	// CallerTable is the table that holds the caller relation/edge.
	CallerTable = "numbers"
	// CallerInverseTable is the table name for the Caller entity.
	// It exists in this package in order to avoid circular dependency with the "caller" package.
	CallerInverseTable = "callers"
	// CallerColumn is the table column denoting the caller relation/edge.
	CallerColumn = "caller_number"
	// LinetypeTable is the table that holds the linetype relation/edge.
	LinetypeTable = "numbers"
	// LinetypeInverseTable is the table name for the LineType entity.
	// It exists in this package in order to avoid circular dependency with the "linetype" package.
	LinetypeInverseTable = "line_types"
	// LinetypeColumn is the table column denoting the linetype relation/edge.
	LinetypeColumn = "line_type_number"
	// CarrierTable is the table that holds the carrier relation/edge.
	CarrierTable = "numbers"
	// CarrierInverseTable is the table name for the Carrier entity.
	// It exists in this package in order to avoid circular dependency with the "carrier" package.
	CarrierInverseTable = "carriers"
	// CarrierColumn is the table column denoting the carrier relation/edge.
	CarrierColumn = "carrier_number"
	// ProviderTable is the table that holds the provider relation/edge.
	ProviderTable = "providers"
	// ProviderInverseTable is the table name for the Provider entity.
	// It exists in this package in order to avoid circular dependency with the "provider" package.
	ProviderInverseTable = "providers"
	// ProviderColumn is the table column denoting the provider relation/edge.
	ProviderColumn = "number_provider"
)

// Columns holds all SQL columns for number fields.
var Columns = []string{
	FieldID,
	FieldNumber,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "numbers"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"caller_number",
	"carrier_number",
	"line_type_number",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Number queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNumber orders the results by the Number field.
func ByNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNumber, opts...).ToFunc()
}

// ByCallerField orders the results by caller field.
func ByCallerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCallerStep(), sql.OrderByField(field, opts...))
	}
}

// ByLinetypeField orders the results by linetype field.
func ByLinetypeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLinetypeStep(), sql.OrderByField(field, opts...))
	}
}

// ByCarrierField orders the results by carrier field.
func ByCarrierField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCarrierStep(), sql.OrderByField(field, opts...))
	}
}

// ByProviderCount orders the results by provider count.
func ByProviderCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProviderStep(), opts...)
	}
}

// ByProvider orders the results by provider terms.
func ByProvider(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProviderStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCallerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CallerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CallerTable, CallerColumn),
	)
}
func newLinetypeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LinetypeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, LinetypeTable, LinetypeColumn),
	)
}
func newCarrierStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CarrierInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CarrierTable, CarrierColumn),
	)
}
func newProviderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProviderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ProviderTable, ProviderColumn),
	)
}
