// Code generated by ent, DO NOT EDIT.

package number

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Number {
	return predicate.Number(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Number {
	return predicate.Number(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Number {
	return predicate.Number(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Number {
	return predicate.Number(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Number {
	return predicate.Number(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Number {
	return predicate.Number(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Number {
	return predicate.Number(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Number {
	return predicate.Number(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Number {
	return predicate.Number(sql.FieldLTE(FieldID, id))
}

// Number applies equality check predicate on the "Number" field. It's identical to NumberEQ.
func Number(v string) predicate.Number {
	return predicate.Number(sql.FieldEQ(FieldNumber, v))
}

// NumberEQ applies the EQ predicate on the "Number" field.
func NumberEQ(v string) predicate.Number {
	return predicate.Number(sql.FieldEQ(FieldNumber, v))
}

// NumberNEQ applies the NEQ predicate on the "Number" field.
func NumberNEQ(v string) predicate.Number {
	return predicate.Number(sql.FieldNEQ(FieldNumber, v))
}

// NumberIn applies the In predicate on the "Number" field.
func NumberIn(vs ...string) predicate.Number {
	return predicate.Number(sql.FieldIn(FieldNumber, vs...))
}

// NumberNotIn applies the NotIn predicate on the "Number" field.
func NumberNotIn(vs ...string) predicate.Number {
	return predicate.Number(sql.FieldNotIn(FieldNumber, vs...))
}

// NumberGT applies the GT predicate on the "Number" field.
func NumberGT(v string) predicate.Number {
	return predicate.Number(sql.FieldGT(FieldNumber, v))
}

// NumberGTE applies the GTE predicate on the "Number" field.
func NumberGTE(v string) predicate.Number {
	return predicate.Number(sql.FieldGTE(FieldNumber, v))
}

// NumberLT applies the LT predicate on the "Number" field.
func NumberLT(v string) predicate.Number {
	return predicate.Number(sql.FieldLT(FieldNumber, v))
}

// NumberLTE applies the LTE predicate on the "Number" field.
func NumberLTE(v string) predicate.Number {
	return predicate.Number(sql.FieldLTE(FieldNumber, v))
}

// NumberContains applies the Contains predicate on the "Number" field.
func NumberContains(v string) predicate.Number {
	return predicate.Number(sql.FieldContains(FieldNumber, v))
}

// NumberHasPrefix applies the HasPrefix predicate on the "Number" field.
func NumberHasPrefix(v string) predicate.Number {
	return predicate.Number(sql.FieldHasPrefix(FieldNumber, v))
}

// NumberHasSuffix applies the HasSuffix predicate on the "Number" field.
func NumberHasSuffix(v string) predicate.Number {
	return predicate.Number(sql.FieldHasSuffix(FieldNumber, v))
}

// NumberEqualFold applies the EqualFold predicate on the "Number" field.
func NumberEqualFold(v string) predicate.Number {
	return predicate.Number(sql.FieldEqualFold(FieldNumber, v))
}

// NumberContainsFold applies the ContainsFold predicate on the "Number" field.
func NumberContainsFold(v string) predicate.Number {
	return predicate.Number(sql.FieldContainsFold(FieldNumber, v))
}

// HasCaller applies the HasEdge predicate on the "caller" edge.
func HasCaller() predicate.Number {
	return predicate.Number(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CallerTable, CallerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCallerWith applies the HasEdge predicate on the "caller" edge with a given conditions (other predicates).
func HasCallerWith(preds ...predicate.Caller) predicate.Number {
	return predicate.Number(func(s *sql.Selector) {
		step := newCallerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLinetype applies the HasEdge predicate on the "linetype" edge.
func HasLinetype() predicate.Number {
	return predicate.Number(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LinetypeTable, LinetypeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLinetypeWith applies the HasEdge predicate on the "linetype" edge with a given conditions (other predicates).
func HasLinetypeWith(preds ...predicate.LineType) predicate.Number {
	return predicate.Number(func(s *sql.Selector) {
		step := newLinetypeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCarrier applies the HasEdge predicate on the "carrier" edge.
func HasCarrier() predicate.Number {
	return predicate.Number(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CarrierTable, CarrierColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCarrierWith applies the HasEdge predicate on the "carrier" edge with a given conditions (other predicates).
func HasCarrierWith(preds ...predicate.Carrier) predicate.Number {
	return predicate.Number(func(s *sql.Selector) {
		step := newCarrierStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProvider applies the HasEdge predicate on the "provider" edge.
func HasProvider() predicate.Number {
	return predicate.Number(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ProviderTable, ProviderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProviderWith applies the HasEdge predicate on the "provider" edge with a given conditions (other predicates).
func HasProviderWith(preds ...predicate.Provider) predicate.Number {
	return predicate.Number(func(s *sql.Selector) {
		step := newProviderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Number) predicate.Number {
	return predicate.Number(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Number) predicate.Number {
	return predicate.Number(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Number) predicate.Number {
	return predicate.Number(sql.NotPredicates(p))
}
