// Code generated by ent, DO NOT EDIT.

package business

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Business {
	return predicate.Business(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Business {
	return predicate.Business(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Business {
	return predicate.Business(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Business {
	return predicate.Business(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Business {
	return predicate.Business(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Business {
	return predicate.Business(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Business {
	return predicate.Business(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Business {
	return predicate.Business(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Business {
	return predicate.Business(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "Name" field. It's identical to NameEQ.
func Name(v string) predicate.Business {
	return predicate.Business(sql.FieldEQ(FieldName, v))
}

// WebsiteLink applies equality check predicate on the "WebsiteLink" field. It's identical to WebsiteLinkEQ.
func WebsiteLink(v string) predicate.Business {
	return predicate.Business(sql.FieldEQ(FieldWebsiteLink, v))
}

// Overview applies equality check predicate on the "Overview" field. It's identical to OverviewEQ.
func Overview(v string) predicate.Business {
	return predicate.Business(sql.FieldEQ(FieldOverview, v))
}

// NameEQ applies the EQ predicate on the "Name" field.
func NameEQ(v string) predicate.Business {
	return predicate.Business(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "Name" field.
func NameNEQ(v string) predicate.Business {
	return predicate.Business(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "Name" field.
func NameIn(vs ...string) predicate.Business {
	return predicate.Business(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "Name" field.
func NameNotIn(vs ...string) predicate.Business {
	return predicate.Business(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "Name" field.
func NameGT(v string) predicate.Business {
	return predicate.Business(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "Name" field.
func NameGTE(v string) predicate.Business {
	return predicate.Business(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "Name" field.
func NameLT(v string) predicate.Business {
	return predicate.Business(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "Name" field.
func NameLTE(v string) predicate.Business {
	return predicate.Business(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "Name" field.
func NameContains(v string) predicate.Business {
	return predicate.Business(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "Name" field.
func NameHasPrefix(v string) predicate.Business {
	return predicate.Business(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "Name" field.
func NameHasSuffix(v string) predicate.Business {
	return predicate.Business(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "Name" field.
func NameIsNil() predicate.Business {
	return predicate.Business(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "Name" field.
func NameNotNil() predicate.Business {
	return predicate.Business(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "Name" field.
func NameEqualFold(v string) predicate.Business {
	return predicate.Business(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "Name" field.
func NameContainsFold(v string) predicate.Business {
	return predicate.Business(sql.FieldContainsFold(FieldName, v))
}

// WebsiteLinkEQ applies the EQ predicate on the "WebsiteLink" field.
func WebsiteLinkEQ(v string) predicate.Business {
	return predicate.Business(sql.FieldEQ(FieldWebsiteLink, v))
}

// WebsiteLinkNEQ applies the NEQ predicate on the "WebsiteLink" field.
func WebsiteLinkNEQ(v string) predicate.Business {
	return predicate.Business(sql.FieldNEQ(FieldWebsiteLink, v))
}

// WebsiteLinkIn applies the In predicate on the "WebsiteLink" field.
func WebsiteLinkIn(vs ...string) predicate.Business {
	return predicate.Business(sql.FieldIn(FieldWebsiteLink, vs...))
}

// WebsiteLinkNotIn applies the NotIn predicate on the "WebsiteLink" field.
func WebsiteLinkNotIn(vs ...string) predicate.Business {
	return predicate.Business(sql.FieldNotIn(FieldWebsiteLink, vs...))
}

// WebsiteLinkGT applies the GT predicate on the "WebsiteLink" field.
func WebsiteLinkGT(v string) predicate.Business {
	return predicate.Business(sql.FieldGT(FieldWebsiteLink, v))
}

// WebsiteLinkGTE applies the GTE predicate on the "WebsiteLink" field.
func WebsiteLinkGTE(v string) predicate.Business {
	return predicate.Business(sql.FieldGTE(FieldWebsiteLink, v))
}

// WebsiteLinkLT applies the LT predicate on the "WebsiteLink" field.
func WebsiteLinkLT(v string) predicate.Business {
	return predicate.Business(sql.FieldLT(FieldWebsiteLink, v))
}

// WebsiteLinkLTE applies the LTE predicate on the "WebsiteLink" field.
func WebsiteLinkLTE(v string) predicate.Business {
	return predicate.Business(sql.FieldLTE(FieldWebsiteLink, v))
}

// WebsiteLinkContains applies the Contains predicate on the "WebsiteLink" field.
func WebsiteLinkContains(v string) predicate.Business {
	return predicate.Business(sql.FieldContains(FieldWebsiteLink, v))
}

// WebsiteLinkHasPrefix applies the HasPrefix predicate on the "WebsiteLink" field.
func WebsiteLinkHasPrefix(v string) predicate.Business {
	return predicate.Business(sql.FieldHasPrefix(FieldWebsiteLink, v))
}

// WebsiteLinkHasSuffix applies the HasSuffix predicate on the "WebsiteLink" field.
func WebsiteLinkHasSuffix(v string) predicate.Business {
	return predicate.Business(sql.FieldHasSuffix(FieldWebsiteLink, v))
}

// WebsiteLinkIsNil applies the IsNil predicate on the "WebsiteLink" field.
func WebsiteLinkIsNil() predicate.Business {
	return predicate.Business(sql.FieldIsNull(FieldWebsiteLink))
}

// WebsiteLinkNotNil applies the NotNil predicate on the "WebsiteLink" field.
func WebsiteLinkNotNil() predicate.Business {
	return predicate.Business(sql.FieldNotNull(FieldWebsiteLink))
}

// WebsiteLinkEqualFold applies the EqualFold predicate on the "WebsiteLink" field.
func WebsiteLinkEqualFold(v string) predicate.Business {
	return predicate.Business(sql.FieldEqualFold(FieldWebsiteLink, v))
}

// WebsiteLinkContainsFold applies the ContainsFold predicate on the "WebsiteLink" field.
func WebsiteLinkContainsFold(v string) predicate.Business {
	return predicate.Business(sql.FieldContainsFold(FieldWebsiteLink, v))
}

// OverviewEQ applies the EQ predicate on the "Overview" field.
func OverviewEQ(v string) predicate.Business {
	return predicate.Business(sql.FieldEQ(FieldOverview, v))
}

// OverviewNEQ applies the NEQ predicate on the "Overview" field.
func OverviewNEQ(v string) predicate.Business {
	return predicate.Business(sql.FieldNEQ(FieldOverview, v))
}

// OverviewIn applies the In predicate on the "Overview" field.
func OverviewIn(vs ...string) predicate.Business {
	return predicate.Business(sql.FieldIn(FieldOverview, vs...))
}

// OverviewNotIn applies the NotIn predicate on the "Overview" field.
func OverviewNotIn(vs ...string) predicate.Business {
	return predicate.Business(sql.FieldNotIn(FieldOverview, vs...))
}

// OverviewGT applies the GT predicate on the "Overview" field.
func OverviewGT(v string) predicate.Business {
	return predicate.Business(sql.FieldGT(FieldOverview, v))
}

// OverviewGTE applies the GTE predicate on the "Overview" field.
func OverviewGTE(v string) predicate.Business {
	return predicate.Business(sql.FieldGTE(FieldOverview, v))
}

// OverviewLT applies the LT predicate on the "Overview" field.
func OverviewLT(v string) predicate.Business {
	return predicate.Business(sql.FieldLT(FieldOverview, v))
}

// OverviewLTE applies the LTE predicate on the "Overview" field.
func OverviewLTE(v string) predicate.Business {
	return predicate.Business(sql.FieldLTE(FieldOverview, v))
}

// OverviewContains applies the Contains predicate on the "Overview" field.
func OverviewContains(v string) predicate.Business {
	return predicate.Business(sql.FieldContains(FieldOverview, v))
}

// OverviewHasPrefix applies the HasPrefix predicate on the "Overview" field.
func OverviewHasPrefix(v string) predicate.Business {
	return predicate.Business(sql.FieldHasPrefix(FieldOverview, v))
}

// OverviewHasSuffix applies the HasSuffix predicate on the "Overview" field.
func OverviewHasSuffix(v string) predicate.Business {
	return predicate.Business(sql.FieldHasSuffix(FieldOverview, v))
}

// OverviewIsNil applies the IsNil predicate on the "Overview" field.
func OverviewIsNil() predicate.Business {
	return predicate.Business(sql.FieldIsNull(FieldOverview))
}

// OverviewNotNil applies the NotNil predicate on the "Overview" field.
func OverviewNotNil() predicate.Business {
	return predicate.Business(sql.FieldNotNull(FieldOverview))
}

// OverviewEqualFold applies the EqualFold predicate on the "Overview" field.
func OverviewEqualFold(v string) predicate.Business {
	return predicate.Business(sql.FieldEqualFold(FieldOverview, v))
}

// OverviewContainsFold applies the ContainsFold predicate on the "Overview" field.
func OverviewContainsFold(v string) predicate.Business {
	return predicate.Business(sql.FieldContainsFold(FieldOverview, v))
}

// HasProvider applies the HasEdge predicate on the "provider" edge.
func HasProvider() predicate.Business {
	return predicate.Business(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, ProviderTable, ProviderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProviderWith applies the HasEdge predicate on the "provider" edge with a given conditions (other predicates).
func HasProviderWith(preds ...predicate.Provider) predicate.Business {
	return predicate.Business(func(s *sql.Selector) {
		step := newProviderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAddress applies the HasEdge predicate on the "address" edge.
func HasAddress() predicate.Business {
	return predicate.Business(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AddressTable, AddressColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAddressWith applies the HasEdge predicate on the "address" edge with a given conditions (other predicates).
func HasAddressWith(preds ...predicate.Address) predicate.Business {
	return predicate.Business(func(s *sql.Selector) {
		step := newAddressStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Business) predicate.Business {
	return predicate.Business(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Business) predicate.Business {
	return predicate.Business(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Business) predicate.Business {
	return predicate.Business(sql.NotPredicates(p))
}
