// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AddressesColumns holds the columns for the "addresses" table.
	AddressesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "prefecture", Type: field.TypeString, Nullable: true},
		{Name: "city", Type: field.TypeString, Nullable: true},
		{Name: "postcode", Type: field.TypeString, Nullable: true},
		{Name: "business_address", Type: field.TypeInt},
	}
	// AddressesTable holds the schema information for the "addresses" table.
	AddressesTable = &schema.Table{
		Name:       "addresses",
		Columns:    AddressesColumns,
		PrimaryKey: []*schema.Column{AddressesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "addresses_businesses_address",
				Columns:    []*schema.Column{AddressesColumns[4]},
				RefColumns: []*schema.Column{BusinessesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// BusinessesColumns holds the columns for the "businesses" table.
	BusinessesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Nullable: true},
		{Name: "website_link", Type: field.TypeString, Nullable: true},
		{Name: "overview", Type: field.TypeString, Nullable: true},
		{Name: "provider_business", Type: field.TypeInt, Unique: true},
	}
	// BusinessesTable holds the schema information for the "businesses" table.
	BusinessesTable = &schema.Table{
		Name:       "businesses",
		Columns:    BusinessesColumns,
		PrimaryKey: []*schema.Column{BusinessesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "businesses_providers_business",
				Columns:    []*schema.Column{BusinessesColumns[4]},
				RefColumns: []*schema.Column{ProvidersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// CallersColumns holds the columns for the "callers" table.
	CallersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "is_fraud", Type: field.TypeBool},
		{Name: "fraud_score", Type: field.TypeInt},
	}
	// CallersTable holds the schema information for the "callers" table.
	CallersTable = &schema.Table{
		Name:       "callers",
		Columns:    CallersColumns,
		PrimaryKey: []*schema.Column{CallersColumns[0]},
	}
	// CarriersColumns holds the columns for the "carriers" table.
	CarriersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true, Nullable: true},
	}
	// CarriersTable holds the schema information for the "carriers" table.
	CarriersTable = &schema.Table{
		Name:       "carriers",
		Columns:    CarriersColumns,
		PrimaryKey: []*schema.Column{CarriersColumns[0]},
	}
	// CommentsColumns holds the columns for the "comments" table.
	CommentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "post_date", Type: field.TypeTime},
		{Name: "comment_text", Type: field.TypeString},
		{Name: "comment_fraud_score", Type: field.TypeInt, Default: 0},
		{Name: "provider_comment", Type: field.TypeInt},
	}
	// CommentsTable holds the schema information for the "comments" table.
	CommentsTable = &schema.Table{
		Name:       "comments",
		Columns:    CommentsColumns,
		PrimaryKey: []*schema.Column{CommentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "comments_providers_comment",
				Columns:    []*schema.Column{CommentsColumns[4]},
				RefColumns: []*schema.Column{ProvidersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// LineTypesColumns holds the columns for the "line_types" table.
	LineTypesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "line_type", Type: field.TypeEnum, Enums: []string{"mobile", "dialfree", "landline", "voip", "unknown", "other"}, Default: "unknown"},
	}
	// LineTypesTable holds the schema information for the "line_types" table.
	LineTypesTable = &schema.Table{
		Name:       "line_types",
		Columns:    LineTypesColumns,
		PrimaryKey: []*schema.Column{LineTypesColumns[0]},
	}
	// NumbersColumns holds the columns for the "numbers" table.
	NumbersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "number", Type: field.TypeString},
		{Name: "caller_number", Type: field.TypeInt},
		{Name: "carrier_number", Type: field.TypeInt, Nullable: true},
		{Name: "line_type_number", Type: field.TypeInt},
	}
	// NumbersTable holds the schema information for the "numbers" table.
	NumbersTable = &schema.Table{
		Name:       "numbers",
		Columns:    NumbersColumns,
		PrimaryKey: []*schema.Column{NumbersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "numbers_callers_number",
				Columns:    []*schema.Column{NumbersColumns[2]},
				RefColumns: []*schema.Column{CallersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "numbers_carriers_number",
				Columns:    []*schema.Column{NumbersColumns[3]},
				RefColumns: []*schema.Column{CarriersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "numbers_line_types_number",
				Columns:    []*schema.Column{NumbersColumns[4]},
				RefColumns: []*schema.Column{LineTypesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ProvidersColumns holds the columns for the "providers" table.
	ProvidersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 2147483647},
		{Name: "number_provider", Type: field.TypeInt},
	}
	// ProvidersTable holds the schema information for the "providers" table.
	ProvidersTable = &schema.Table{
		Name:       "providers",
		Columns:    ProvidersColumns,
		PrimaryKey: []*schema.Column{ProvidersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "providers_numbers_provider",
				Columns:    []*schema.Column{ProvidersColumns[2]},
				RefColumns: []*schema.Column{NumbersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AddressesTable,
		BusinessesTable,
		CallersTable,
		CarriersTable,
		CommentsTable,
		LineTypesTable,
		NumbersTable,
		ProvidersTable,
	}
)

func init() {
	AddressesTable.ForeignKeys[0].RefTable = BusinessesTable
	BusinessesTable.ForeignKeys[0].RefTable = ProvidersTable
	CommentsTable.ForeignKeys[0].RefTable = ProvidersTable
	NumbersTable.ForeignKeys[0].RefTable = CallersTable
	NumbersTable.ForeignKeys[1].RefTable = CarriersTable
	NumbersTable.ForeignKeys[2].RefTable = LineTypesTable
	ProvidersTable.ForeignKeys[0].RefTable = NumbersTable
}
