// Code generated by ent, DO NOT EDIT.

package carrier

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the carrier type in the database.
	Label = "carrier"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeNumber holds the string denoting the number edge name in mutations.
	EdgeNumber = "number"
	// Table holds the table name of the carrier in the database.
	Table = "carriers"
	// NumberTable is the table that holds the number relation/edge.
	NumberTable = "numbers"
	// NumberInverseTable is the table name for the Number entity.
	// It exists in this package in order to avoid circular dependency with the "number" package.
	NumberInverseTable = "numbers"
	// NumberColumn is the table column denoting the number relation/edge.
	NumberColumn = "carrier_number"
)

// Columns holds all SQL columns for carrier fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Carrier queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the Name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByNumberCount orders the results by number count.
func ByNumberCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newNumberStep(), opts...)
	}
}

// ByNumber orders the results by number terms.
func ByNumber(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNumberStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newNumberStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NumberInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, NumberTable, NumberColumn),
	)
}
