// Code generated by ent, DO NOT EDIT.

package carrier

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Carrier {
	return predicate.Carrier(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Carrier {
	return predicate.Carrier(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Carrier {
	return predicate.Carrier(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Carrier {
	return predicate.Carrier(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Carrier {
	return predicate.Carrier(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Carrier {
	return predicate.Carrier(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Carrier {
	return predicate.Carrier(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Carrier {
	return predicate.Carrier(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Carrier {
	return predicate.Carrier(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "Name" field. It's identical to NameEQ.
func Name(v string) predicate.Carrier {
	return predicate.Carrier(sql.FieldEQ(FieldName, v))
}

// NameEQ applies the EQ predicate on the "Name" field.
func NameEQ(v string) predicate.Carrier {
	return predicate.Carrier(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "Name" field.
func NameNEQ(v string) predicate.Carrier {
	return predicate.Carrier(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "Name" field.
func NameIn(vs ...string) predicate.Carrier {
	return predicate.Carrier(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "Name" field.
func NameNotIn(vs ...string) predicate.Carrier {
	return predicate.Carrier(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "Name" field.
func NameGT(v string) predicate.Carrier {
	return predicate.Carrier(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "Name" field.
func NameGTE(v string) predicate.Carrier {
	return predicate.Carrier(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "Name" field.
func NameLT(v string) predicate.Carrier {
	return predicate.Carrier(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "Name" field.
func NameLTE(v string) predicate.Carrier {
	return predicate.Carrier(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "Name" field.
func NameContains(v string) predicate.Carrier {
	return predicate.Carrier(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "Name" field.
func NameHasPrefix(v string) predicate.Carrier {
	return predicate.Carrier(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "Name" field.
func NameHasSuffix(v string) predicate.Carrier {
	return predicate.Carrier(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "Name" field.
func NameIsNil() predicate.Carrier {
	return predicate.Carrier(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "Name" field.
func NameNotNil() predicate.Carrier {
	return predicate.Carrier(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "Name" field.
func NameEqualFold(v string) predicate.Carrier {
	return predicate.Carrier(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "Name" field.
func NameContainsFold(v string) predicate.Carrier {
	return predicate.Carrier(sql.FieldContainsFold(FieldName, v))
}

// HasNumber applies the HasEdge predicate on the "number" edge.
func HasNumber() predicate.Carrier {
	return predicate.Carrier(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, NumberTable, NumberColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNumberWith applies the HasEdge predicate on the "number" edge with a given conditions (other predicates).
func HasNumberWith(preds ...predicate.Number) predicate.Carrier {
	return predicate.Carrier(func(s *sql.Selector) {
		step := newNumberStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Carrier) predicate.Carrier {
	return predicate.Carrier(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Carrier) predicate.Carrier {
	return predicate.Carrier(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Carrier) predicate.Carrier {
	return predicate.Carrier(sql.NotPredicates(p))
}
