// Code generated by ent, DO NOT EDIT.

package linetype

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Blanco0420/Phone-Number-Check/backend/providers"
)

const (
	// Label holds the string label denoting the linetype type in the database.
	Label = "line_type"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLineType holds the string denoting the linetype field in the database.
	FieldLineType = "line_type"
	// EdgeNumber holds the string denoting the number edge name in mutations.
	EdgeNumber = "number"
	// Table holds the table name of the linetype in the database.
	Table = "line_types"
	// NumberTable is the table that holds the number relation/edge.
	NumberTable = "numbers"
	// NumberInverseTable is the table name for the Number entity.
	// It exists in this package in order to avoid circular dependency with the "number" package.
	NumberInverseTable = "numbers"
	// NumberColumn is the table column denoting the number relation/edge.
	NumberColumn = "line_type_number"
)

// Columns holds all SQL columns for linetype fields.
var Columns = []string{
	FieldID,
	FieldLineType,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

const DefaultLineType providers.LineType = "unknown"

// LineTypeValidator is a validator for the "LineType" field enum values. It is called by the builders before save.
func LineTypeValidator(_linetype providers.LineType) error {
	switch _linetype {
	case "mobile", "dialfree", "landline", "voip", "unknown", "other":
		return nil
	default:
		return fmt.Errorf("linetype: invalid enum value for LineType field: %q", _linetype)
	}
}

// OrderOption defines the ordering options for the LineType queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLineType orders the results by the LineType field.
func ByLineType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLineType, opts...).ToFunc()
}

// ByNumberCount orders the results by number count.
func ByNumberCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newNumberStep(), opts...)
	}
}

// ByNumber orders the results by number terms.
func ByNumber(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNumberStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newNumberStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NumberInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, NumberTable, NumberColumn),
	)
}
