// Code generated by ent, DO NOT EDIT.

package linetype

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/predicate"
	"github.com/Blanco0420/Phone-Number-Check/backend/providers"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.LineType {
	return predicate.LineType(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.LineType {
	return predicate.LineType(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.LineType {
	return predicate.LineType(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.LineType {
	return predicate.LineType(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.LineType {
	return predicate.LineType(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.LineType {
	return predicate.LineType(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.LineType {
	return predicate.LineType(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.LineType {
	return predicate.LineType(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.LineType {
	return predicate.LineType(sql.FieldLTE(FieldID, id))
}

// LineTypeEQ applies the EQ predicate on the "LineType" field.
func LineTypeEQ(v providers.LineType) predicate.LineType {
	vc := v
	return predicate.LineType(sql.FieldEQ(FieldLineType, vc))
}

// LineTypeNEQ applies the NEQ predicate on the "LineType" field.
func LineTypeNEQ(v providers.LineType) predicate.LineType {
	vc := v
	return predicate.LineType(sql.FieldNEQ(FieldLineType, vc))
}

// LineTypeIn applies the In predicate on the "LineType" field.
func LineTypeIn(vs ...providers.LineType) predicate.LineType {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.LineType(sql.FieldIn(FieldLineType, v...))
}

// LineTypeNotIn applies the NotIn predicate on the "LineType" field.
func LineTypeNotIn(vs ...providers.LineType) predicate.LineType {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.LineType(sql.FieldNotIn(FieldLineType, v...))
}

// HasNumber applies the HasEdge predicate on the "number" edge.
func HasNumber() predicate.LineType {
	return predicate.LineType(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, NumberTable, NumberColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNumberWith applies the HasEdge predicate on the "number" edge with a given conditions (other predicates).
func HasNumberWith(preds ...predicate.Number) predicate.LineType {
	return predicate.LineType(func(s *sql.Selector) {
		step := newNumberStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LineType) predicate.LineType {
	return predicate.LineType(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LineType) predicate.LineType {
	return predicate.LineType(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LineType) predicate.LineType {
	return predicate.LineType(sql.NotPredicates(p))
}
