// Code generated by ent, DO NOT EDIT.

package caller

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the caller type in the database.
	Label = "caller"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIsFraud holds the string denoting the isfraud field in the database.
	FieldIsFraud = "is_fraud"
	// FieldFraudScore holds the string denoting the fraudscore field in the database.
	FieldFraudScore = "fraud_score"
	// EdgeNumber holds the string denoting the number edge name in mutations.
	EdgeNumber = "number"
	// Table holds the table name of the caller in the database.
	Table = "callers"
	// NumberTable is the table that holds the number relation/edge.
	NumberTable = "numbers"
	// NumberInverseTable is the table name for the Number entity.
	// It exists in this package in order to avoid circular dependency with the "number" package.
	NumberInverseTable = "numbers"
	// NumberColumn is the table column denoting the number relation/edge.
	NumberColumn = "caller_number"
)

// Columns holds all SQL columns for caller fields.
var Columns = []string{
	FieldID,
	FieldIsFraud,
	FieldFraudScore,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Caller queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByIsFraud orders the results by the IsFraud field.
func ByIsFraud(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsFraud, opts...).ToFunc()
}

// ByFraudScore orders the results by the FraudScore field.
func ByFraudScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFraudScore, opts...).ToFunc()
}

// ByNumberCount orders the results by number count.
func ByNumberCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newNumberStep(), opts...)
	}
}

// ByNumber orders the results by number terms.
func ByNumber(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNumberStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newNumberStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NumberInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, NumberTable, NumberColumn),
	)
}
