// Code generated by ent, DO NOT EDIT.

package caller

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Caller {
	return predicate.Caller(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Caller {
	return predicate.Caller(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Caller {
	return predicate.Caller(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Caller {
	return predicate.Caller(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Caller {
	return predicate.Caller(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Caller {
	return predicate.Caller(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Caller {
	return predicate.Caller(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Caller {
	return predicate.Caller(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Caller {
	return predicate.Caller(sql.FieldLTE(FieldID, id))
}

// IsFraud applies equality check predicate on the "IsFraud" field. It's identical to IsFraudEQ.
func IsFraud(v bool) predicate.Caller {
	return predicate.Caller(sql.FieldEQ(FieldIsFraud, v))
}

// FraudScore applies equality check predicate on the "FraudScore" field. It's identical to FraudScoreEQ.
func FraudScore(v int) predicate.Caller {
	return predicate.Caller(sql.FieldEQ(FieldFraudScore, v))
}

// IsFraudEQ applies the EQ predicate on the "IsFraud" field.
func IsFraudEQ(v bool) predicate.Caller {
	return predicate.Caller(sql.FieldEQ(FieldIsFraud, v))
}

// IsFraudNEQ applies the NEQ predicate on the "IsFraud" field.
func IsFraudNEQ(v bool) predicate.Caller {
	return predicate.Caller(sql.FieldNEQ(FieldIsFraud, v))
}

// FraudScoreEQ applies the EQ predicate on the "FraudScore" field.
func FraudScoreEQ(v int) predicate.Caller {
	return predicate.Caller(sql.FieldEQ(FieldFraudScore, v))
}

// FraudScoreNEQ applies the NEQ predicate on the "FraudScore" field.
func FraudScoreNEQ(v int) predicate.Caller {
	return predicate.Caller(sql.FieldNEQ(FieldFraudScore, v))
}

// FraudScoreIn applies the In predicate on the "FraudScore" field.
func FraudScoreIn(vs ...int) predicate.Caller {
	return predicate.Caller(sql.FieldIn(FieldFraudScore, vs...))
}

// FraudScoreNotIn applies the NotIn predicate on the "FraudScore" field.
func FraudScoreNotIn(vs ...int) predicate.Caller {
	return predicate.Caller(sql.FieldNotIn(FieldFraudScore, vs...))
}

// FraudScoreGT applies the GT predicate on the "FraudScore" field.
func FraudScoreGT(v int) predicate.Caller {
	return predicate.Caller(sql.FieldGT(FieldFraudScore, v))
}

// FraudScoreGTE applies the GTE predicate on the "FraudScore" field.
func FraudScoreGTE(v int) predicate.Caller {
	return predicate.Caller(sql.FieldGTE(FieldFraudScore, v))
}

// FraudScoreLT applies the LT predicate on the "FraudScore" field.
func FraudScoreLT(v int) predicate.Caller {
	return predicate.Caller(sql.FieldLT(FieldFraudScore, v))
}

// FraudScoreLTE applies the LTE predicate on the "FraudScore" field.
func FraudScoreLTE(v int) predicate.Caller {
	return predicate.Caller(sql.FieldLTE(FieldFraudScore, v))
}

// HasNumber applies the HasEdge predicate on the "number" edge.
func HasNumber() predicate.Caller {
	return predicate.Caller(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, NumberTable, NumberColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNumberWith applies the HasEdge predicate on the "number" edge with a given conditions (other predicates).
func HasNumberWith(preds ...predicate.Number) predicate.Caller {
	return predicate.Caller(func(s *sql.Selector) {
		step := newNumberStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Caller) predicate.Caller {
	return predicate.Caller(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Caller) predicate.Caller {
	return predicate.Caller(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Caller) predicate.Caller {
	return predicate.Caller(sql.NotPredicates(p))
}
