// Code generated by ent, DO NOT EDIT.

package comment

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the comment type in the database.
	Label = "comment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPostDate holds the string denoting the postdate field in the database.
	FieldPostDate = "post_date"
	// FieldCommentText holds the string denoting the commenttext field in the database.
	FieldCommentText = "comment_text"
	// FieldCommentFraudScore holds the string denoting the commentfraudscore field in the database.
	FieldCommentFraudScore = "comment_fraud_score"
	// EdgeProvider holds the string denoting the provider edge name in mutations.
	EdgeProvider = "provider"
	// Table holds the table name of the comment in the database.
	Table = "comments"
	// ProviderTable is the table that holds the provider relation/edge.
	ProviderTable = "comments"
	// ProviderInverseTable is the table name for the Provider entity.
	// It exists in this package in order to avoid circular dependency with the "provider" package.
	ProviderInverseTable = "providers"
	// ProviderColumn is the table column denoting the provider relation/edge.
	ProviderColumn = "provider_comment"
)

// Columns holds all SQL columns for comment fields.
var Columns = []string{
	FieldID,
	FieldPostDate,
	FieldCommentText,
	FieldCommentFraudScore,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "comments"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"provider_comment",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCommentFraudScore holds the default value on creation for the "CommentFraudScore" field.
	DefaultCommentFraudScore int
)

// OrderOption defines the ordering options for the Comment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPostDate orders the results by the PostDate field.
func ByPostDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPostDate, opts...).ToFunc()
}

// ByCommentText orders the results by the CommentText field.
func ByCommentText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommentText, opts...).ToFunc()
}

// ByCommentFraudScore orders the results by the CommentFraudScore field.
func ByCommentFraudScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommentFraudScore, opts...).ToFunc()
}

// ByProviderField orders the results by provider field.
func ByProviderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProviderStep(), sql.OrderByField(field, opts...))
	}
}
func newProviderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProviderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProviderTable, ProviderColumn),
	)
}
