// Code generated by ent, DO NOT EDIT.

package comment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Comment {
	return predicate.Comment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Comment {
	return predicate.Comment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Comment {
	return predicate.Comment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Comment {
	return predicate.Comment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Comment {
	return predicate.Comment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Comment {
	return predicate.Comment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Comment {
	return predicate.Comment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Comment {
	return predicate.Comment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Comment {
	return predicate.Comment(sql.FieldLTE(FieldID, id))
}

// PostDate applies equality check predicate on the "PostDate" field. It's identical to PostDateEQ.
func PostDate(v time.Time) predicate.Comment {
	return predicate.Comment(sql.FieldEQ(FieldPostDate, v))
}

// CommentText applies equality check predicate on the "CommentText" field. It's identical to CommentTextEQ.
func CommentText(v string) predicate.Comment {
	return predicate.Comment(sql.FieldEQ(FieldCommentText, v))
}

// CommentFraudScore applies equality check predicate on the "CommentFraudScore" field. It's identical to CommentFraudScoreEQ.
func CommentFraudScore(v int) predicate.Comment {
	return predicate.Comment(sql.FieldEQ(FieldCommentFraudScore, v))
}

// PostDateEQ applies the EQ predicate on the "PostDate" field.
func PostDateEQ(v time.Time) predicate.Comment {
	return predicate.Comment(sql.FieldEQ(FieldPostDate, v))
}

// PostDateNEQ applies the NEQ predicate on the "PostDate" field.
func PostDateNEQ(v time.Time) predicate.Comment {
	return predicate.Comment(sql.FieldNEQ(FieldPostDate, v))
}

// PostDateIn applies the In predicate on the "PostDate" field.
func PostDateIn(vs ...time.Time) predicate.Comment {
	return predicate.Comment(sql.FieldIn(FieldPostDate, vs...))
}

// PostDateNotIn applies the NotIn predicate on the "PostDate" field.
func PostDateNotIn(vs ...time.Time) predicate.Comment {
	return predicate.Comment(sql.FieldNotIn(FieldPostDate, vs...))
}

// PostDateGT applies the GT predicate on the "PostDate" field.
func PostDateGT(v time.Time) predicate.Comment {
	return predicate.Comment(sql.FieldGT(FieldPostDate, v))
}

// PostDateGTE applies the GTE predicate on the "PostDate" field.
func PostDateGTE(v time.Time) predicate.Comment {
	return predicate.Comment(sql.FieldGTE(FieldPostDate, v))
}

// PostDateLT applies the LT predicate on the "PostDate" field.
func PostDateLT(v time.Time) predicate.Comment {
	return predicate.Comment(sql.FieldLT(FieldPostDate, v))
}

// PostDateLTE applies the LTE predicate on the "PostDate" field.
func PostDateLTE(v time.Time) predicate.Comment {
	return predicate.Comment(sql.FieldLTE(FieldPostDate, v))
}

// CommentTextEQ applies the EQ predicate on the "CommentText" field.
func CommentTextEQ(v string) predicate.Comment {
	return predicate.Comment(sql.FieldEQ(FieldCommentText, v))
}

// CommentTextNEQ applies the NEQ predicate on the "CommentText" field.
func CommentTextNEQ(v string) predicate.Comment {
	return predicate.Comment(sql.FieldNEQ(FieldCommentText, v))
}

// CommentTextIn applies the In predicate on the "CommentText" field.
func CommentTextIn(vs ...string) predicate.Comment {
	return predicate.Comment(sql.FieldIn(FieldCommentText, vs...))
}

// CommentTextNotIn applies the NotIn predicate on the "CommentText" field.
func CommentTextNotIn(vs ...string) predicate.Comment {
	return predicate.Comment(sql.FieldNotIn(FieldCommentText, vs...))
}

// CommentTextGT applies the GT predicate on the "CommentText" field.
func CommentTextGT(v string) predicate.Comment {
	return predicate.Comment(sql.FieldGT(FieldCommentText, v))
}

// CommentTextGTE applies the GTE predicate on the "CommentText" field.
func CommentTextGTE(v string) predicate.Comment {
	return predicate.Comment(sql.FieldGTE(FieldCommentText, v))
}

// CommentTextLT applies the LT predicate on the "CommentText" field.
func CommentTextLT(v string) predicate.Comment {
	return predicate.Comment(sql.FieldLT(FieldCommentText, v))
}

// CommentTextLTE applies the LTE predicate on the "CommentText" field.
func CommentTextLTE(v string) predicate.Comment {
	return predicate.Comment(sql.FieldLTE(FieldCommentText, v))
}

// CommentTextContains applies the Contains predicate on the "CommentText" field.
func CommentTextContains(v string) predicate.Comment {
	return predicate.Comment(sql.FieldContains(FieldCommentText, v))
}

// CommentTextHasPrefix applies the HasPrefix predicate on the "CommentText" field.
func CommentTextHasPrefix(v string) predicate.Comment {
	return predicate.Comment(sql.FieldHasPrefix(FieldCommentText, v))
}

// CommentTextHasSuffix applies the HasSuffix predicate on the "CommentText" field.
func CommentTextHasSuffix(v string) predicate.Comment {
	return predicate.Comment(sql.FieldHasSuffix(FieldCommentText, v))
}

// CommentTextEqualFold applies the EqualFold predicate on the "CommentText" field.
func CommentTextEqualFold(v string) predicate.Comment {
	return predicate.Comment(sql.FieldEqualFold(FieldCommentText, v))
}

// CommentTextContainsFold applies the ContainsFold predicate on the "CommentText" field.
func CommentTextContainsFold(v string) predicate.Comment {
	return predicate.Comment(sql.FieldContainsFold(FieldCommentText, v))
}

// CommentFraudScoreEQ applies the EQ predicate on the "CommentFraudScore" field.
func CommentFraudScoreEQ(v int) predicate.Comment {
	return predicate.Comment(sql.FieldEQ(FieldCommentFraudScore, v))
}

// CommentFraudScoreNEQ applies the NEQ predicate on the "CommentFraudScore" field.
func CommentFraudScoreNEQ(v int) predicate.Comment {
	return predicate.Comment(sql.FieldNEQ(FieldCommentFraudScore, v))
}

// CommentFraudScoreIn applies the In predicate on the "CommentFraudScore" field.
func CommentFraudScoreIn(vs ...int) predicate.Comment {
	return predicate.Comment(sql.FieldIn(FieldCommentFraudScore, vs...))
}

// CommentFraudScoreNotIn applies the NotIn predicate on the "CommentFraudScore" field.
func CommentFraudScoreNotIn(vs ...int) predicate.Comment {
	return predicate.Comment(sql.FieldNotIn(FieldCommentFraudScore, vs...))
}

// CommentFraudScoreGT applies the GT predicate on the "CommentFraudScore" field.
func CommentFraudScoreGT(v int) predicate.Comment {
	return predicate.Comment(sql.FieldGT(FieldCommentFraudScore, v))
}

// CommentFraudScoreGTE applies the GTE predicate on the "CommentFraudScore" field.
func CommentFraudScoreGTE(v int) predicate.Comment {
	return predicate.Comment(sql.FieldGTE(FieldCommentFraudScore, v))
}

// CommentFraudScoreLT applies the LT predicate on the "CommentFraudScore" field.
func CommentFraudScoreLT(v int) predicate.Comment {
	return predicate.Comment(sql.FieldLT(FieldCommentFraudScore, v))
}

// CommentFraudScoreLTE applies the LTE predicate on the "CommentFraudScore" field.
func CommentFraudScoreLTE(v int) predicate.Comment {
	return predicate.Comment(sql.FieldLTE(FieldCommentFraudScore, v))
}

// HasProvider applies the HasEdge predicate on the "provider" edge.
func HasProvider() predicate.Comment {
	return predicate.Comment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProviderTable, ProviderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProviderWith applies the HasEdge predicate on the "provider" edge with a given conditions (other predicates).
func HasProviderWith(preds ...predicate.Provider) predicate.Comment {
	return predicate.Comment(func(s *sql.Selector) {
		step := newProviderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Comment) predicate.Comment {
	return predicate.Comment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Comment) predicate.Comment {
	return predicate.Comment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Comment) predicate.Comment {
	return predicate.Comment(sql.NotPredicates(p))
}
