// Code generated by ent, DO NOT EDIT.

package address

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Blanco0420/Phone-Number-Check/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Address {
	return predicate.Address(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Address {
	return predicate.Address(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Address {
	return predicate.Address(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Address {
	return predicate.Address(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Address {
	return predicate.Address(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Address {
	return predicate.Address(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Address {
	return predicate.Address(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Address {
	return predicate.Address(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Address {
	return predicate.Address(sql.FieldLTE(FieldID, id))
}

// Prefecture applies equality check predicate on the "Prefecture" field. It's identical to PrefectureEQ.
func Prefecture(v string) predicate.Address {
	return predicate.Address(sql.FieldEQ(FieldPrefecture, v))
}

// City applies equality check predicate on the "City" field. It's identical to CityEQ.
func City(v string) predicate.Address {
	return predicate.Address(sql.FieldEQ(FieldCity, v))
}

// Postcode applies equality check predicate on the "Postcode" field. It's identical to PostcodeEQ.
func Postcode(v string) predicate.Address {
	return predicate.Address(sql.FieldEQ(FieldPostcode, v))
}

// PrefectureEQ applies the EQ predicate on the "Prefecture" field.
func PrefectureEQ(v string) predicate.Address {
	return predicate.Address(sql.FieldEQ(FieldPrefecture, v))
}

// PrefectureNEQ applies the NEQ predicate on the "Prefecture" field.
func PrefectureNEQ(v string) predicate.Address {
	return predicate.Address(sql.FieldNEQ(FieldPrefecture, v))
}

// PrefectureIn applies the In predicate on the "Prefecture" field.
func PrefectureIn(vs ...string) predicate.Address {
	return predicate.Address(sql.FieldIn(FieldPrefecture, vs...))
}

// PrefectureNotIn applies the NotIn predicate on the "Prefecture" field.
func PrefectureNotIn(vs ...string) predicate.Address {
	return predicate.Address(sql.FieldNotIn(FieldPrefecture, vs...))
}

// PrefectureGT applies the GT predicate on the "Prefecture" field.
func PrefectureGT(v string) predicate.Address {
	return predicate.Address(sql.FieldGT(FieldPrefecture, v))
}

// PrefectureGTE applies the GTE predicate on the "Prefecture" field.
func PrefectureGTE(v string) predicate.Address {
	return predicate.Address(sql.FieldGTE(FieldPrefecture, v))
}

// PrefectureLT applies the LT predicate on the "Prefecture" field.
func PrefectureLT(v string) predicate.Address {
	return predicate.Address(sql.FieldLT(FieldPrefecture, v))
}

// PrefectureLTE applies the LTE predicate on the "Prefecture" field.
func PrefectureLTE(v string) predicate.Address {
	return predicate.Address(sql.FieldLTE(FieldPrefecture, v))
}

// PrefectureContains applies the Contains predicate on the "Prefecture" field.
func PrefectureContains(v string) predicate.Address {
	return predicate.Address(sql.FieldContains(FieldPrefecture, v))
}

// PrefectureHasPrefix applies the HasPrefix predicate on the "Prefecture" field.
func PrefectureHasPrefix(v string) predicate.Address {
	return predicate.Address(sql.FieldHasPrefix(FieldPrefecture, v))
}

// PrefectureHasSuffix applies the HasSuffix predicate on the "Prefecture" field.
func PrefectureHasSuffix(v string) predicate.Address {
	return predicate.Address(sql.FieldHasSuffix(FieldPrefecture, v))
}

// PrefectureIsNil applies the IsNil predicate on the "Prefecture" field.
func PrefectureIsNil() predicate.Address {
	return predicate.Address(sql.FieldIsNull(FieldPrefecture))
}

// PrefectureNotNil applies the NotNil predicate on the "Prefecture" field.
func PrefectureNotNil() predicate.Address {
	return predicate.Address(sql.FieldNotNull(FieldPrefecture))
}

// PrefectureEqualFold applies the EqualFold predicate on the "Prefecture" field.
func PrefectureEqualFold(v string) predicate.Address {
	return predicate.Address(sql.FieldEqualFold(FieldPrefecture, v))
}

// PrefectureContainsFold applies the ContainsFold predicate on the "Prefecture" field.
func PrefectureContainsFold(v string) predicate.Address {
	return predicate.Address(sql.FieldContainsFold(FieldPrefecture, v))
}

// CityEQ applies the EQ predicate on the "City" field.
func CityEQ(v string) predicate.Address {
	return predicate.Address(sql.FieldEQ(FieldCity, v))
}

// CityNEQ applies the NEQ predicate on the "City" field.
func CityNEQ(v string) predicate.Address {
	return predicate.Address(sql.FieldNEQ(FieldCity, v))
}

// CityIn applies the In predicate on the "City" field.
func CityIn(vs ...string) predicate.Address {
	return predicate.Address(sql.FieldIn(FieldCity, vs...))
}

// CityNotIn applies the NotIn predicate on the "City" field.
func CityNotIn(vs ...string) predicate.Address {
	return predicate.Address(sql.FieldNotIn(FieldCity, vs...))
}

// CityGT applies the GT predicate on the "City" field.
func CityGT(v string) predicate.Address {
	return predicate.Address(sql.FieldGT(FieldCity, v))
}

// CityGTE applies the GTE predicate on the "City" field.
func CityGTE(v string) predicate.Address {
	return predicate.Address(sql.FieldGTE(FieldCity, v))
}

// CityLT applies the LT predicate on the "City" field.
func CityLT(v string) predicate.Address {
	return predicate.Address(sql.FieldLT(FieldCity, v))
}

// CityLTE applies the LTE predicate on the "City" field.
func CityLTE(v string) predicate.Address {
	return predicate.Address(sql.FieldLTE(FieldCity, v))
}

// CityContains applies the Contains predicate on the "City" field.
func CityContains(v string) predicate.Address {
	return predicate.Address(sql.FieldContains(FieldCity, v))
}

// CityHasPrefix applies the HasPrefix predicate on the "City" field.
func CityHasPrefix(v string) predicate.Address {
	return predicate.Address(sql.FieldHasPrefix(FieldCity, v))
}

// CityHasSuffix applies the HasSuffix predicate on the "City" field.
func CityHasSuffix(v string) predicate.Address {
	return predicate.Address(sql.FieldHasSuffix(FieldCity, v))
}

// CityIsNil applies the IsNil predicate on the "City" field.
func CityIsNil() predicate.Address {
	return predicate.Address(sql.FieldIsNull(FieldCity))
}

// CityNotNil applies the NotNil predicate on the "City" field.
func CityNotNil() predicate.Address {
	return predicate.Address(sql.FieldNotNull(FieldCity))
}

// CityEqualFold applies the EqualFold predicate on the "City" field.
func CityEqualFold(v string) predicate.Address {
	return predicate.Address(sql.FieldEqualFold(FieldCity, v))
}

// CityContainsFold applies the ContainsFold predicate on the "City" field.
func CityContainsFold(v string) predicate.Address {
	return predicate.Address(sql.FieldContainsFold(FieldCity, v))
}

// PostcodeEQ applies the EQ predicate on the "Postcode" field.
func PostcodeEQ(v string) predicate.Address {
	return predicate.Address(sql.FieldEQ(FieldPostcode, v))
}

// PostcodeNEQ applies the NEQ predicate on the "Postcode" field.
func PostcodeNEQ(v string) predicate.Address {
	return predicate.Address(sql.FieldNEQ(FieldPostcode, v))
}

// PostcodeIn applies the In predicate on the "Postcode" field.
func PostcodeIn(vs ...string) predicate.Address {
	return predicate.Address(sql.FieldIn(FieldPostcode, vs...))
}

// PostcodeNotIn applies the NotIn predicate on the "Postcode" field.
func PostcodeNotIn(vs ...string) predicate.Address {
	return predicate.Address(sql.FieldNotIn(FieldPostcode, vs...))
}

// PostcodeGT applies the GT predicate on the "Postcode" field.
func PostcodeGT(v string) predicate.Address {
	return predicate.Address(sql.FieldGT(FieldPostcode, v))
}

// PostcodeGTE applies the GTE predicate on the "Postcode" field.
func PostcodeGTE(v string) predicate.Address {
	return predicate.Address(sql.FieldGTE(FieldPostcode, v))
}

// PostcodeLT applies the LT predicate on the "Postcode" field.
func PostcodeLT(v string) predicate.Address {
	return predicate.Address(sql.FieldLT(FieldPostcode, v))
}

// PostcodeLTE applies the LTE predicate on the "Postcode" field.
func PostcodeLTE(v string) predicate.Address {
	return predicate.Address(sql.FieldLTE(FieldPostcode, v))
}

// PostcodeContains applies the Contains predicate on the "Postcode" field.
func PostcodeContains(v string) predicate.Address {
	return predicate.Address(sql.FieldContains(FieldPostcode, v))
}

// PostcodeHasPrefix applies the HasPrefix predicate on the "Postcode" field.
func PostcodeHasPrefix(v string) predicate.Address {
	return predicate.Address(sql.FieldHasPrefix(FieldPostcode, v))
}

// PostcodeHasSuffix applies the HasSuffix predicate on the "Postcode" field.
func PostcodeHasSuffix(v string) predicate.Address {
	return predicate.Address(sql.FieldHasSuffix(FieldPostcode, v))
}

// PostcodeIsNil applies the IsNil predicate on the "Postcode" field.
func PostcodeIsNil() predicate.Address {
	return predicate.Address(sql.FieldIsNull(FieldPostcode))
}

// PostcodeNotNil applies the NotNil predicate on the "Postcode" field.
func PostcodeNotNil() predicate.Address {
	return predicate.Address(sql.FieldNotNull(FieldPostcode))
}

// PostcodeEqualFold applies the EqualFold predicate on the "Postcode" field.
func PostcodeEqualFold(v string) predicate.Address {
	return predicate.Address(sql.FieldEqualFold(FieldPostcode, v))
}

// PostcodeContainsFold applies the ContainsFold predicate on the "Postcode" field.
func PostcodeContainsFold(v string) predicate.Address {
	return predicate.Address(sql.FieldContainsFold(FieldPostcode, v))
}

// HasBusiness applies the HasEdge predicate on the "business" edge.
func HasBusiness() predicate.Address {
	return predicate.Address(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BusinessTable, BusinessColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBusinessWith applies the HasEdge predicate on the "business" edge with a given conditions (other predicates).
func HasBusinessWith(preds ...predicate.Business) predicate.Address {
	return predicate.Address(func(s *sql.Selector) {
		step := newBusinessStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Address) predicate.Address {
	return predicate.Address(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Address) predicate.Address {
	return predicate.Address(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Address) predicate.Address {
	return predicate.Address(sql.NotPredicates(p))
}
